package pli

/*

Since https://github.com/virtualvinodh/aksharamukha already has a working transliteration algorithm for IAST→Katakana there is not point in working on this anymore.

Status before scraping:
~580 Syllables remaining to map. Found when transliterating Patimokkha + DN1 + MahaSamaya. There may be more, rarer syllable in the wild.
Some of them aren't missing but caused by bugs in the syllable parser of libgiita


 ""____"jā⸱nā⸱mi⸱’ a⸱pas⸱saṁ, ‘"
 "ab"____"tat⸱tha so  bhik⸱khu ab⸱bhe⸱tab⸱bo, "
 "ac"____"ac⸱chin⸱na⸱cī⸱va⸱ro vā ho⸱ti bhik⸱khu naṭ⸱ṭha⸱cī⸱va⸱ro vā, "
 "ad"____"bhik⸱khu⸱no pa⸱n’e⸱va ad⸱dhā⸱na⸱mag⸱ga⸱pa⸱ti⸱pan⸱nas⸱sa e⸱ḷa⸱ka⸱lo⸱mā⸱ni up⸱paj⸱jey⸱yuṁ ā⸱kaṅ⸱kha⸱mā⸱ne⸱na bhik⸱khu⸱nā pa⸱ṭig⸱ga⸱he⸱tab⸱bā⸱ni, "
 "ag"____"ma⸱hal⸱la⸱kaṁ pa⸱na bhik⸱khu⸱nā vi⸱hā⸱raṁ kā⸱ra⸱ya⸱mā⸱ne⸱na yā⸱va dvā⸱ra⸱ko⸱sā ag⸱ga⸱laṭ⸱ṭha⸱pa⸱nā⸱ya ā⸱lo⸱ka⸱san⸱dhi⸱pa⸱ri⸱kam⸱mā⸱ya dvit⸱tic⸱cha⸱da⸱nas⸱sa pa⸱ri⸱yā⸱yaṁ ap⸱pa⸱ha⸱ri⸱te ṭhi⸱te⸱na a⸱dhiṭ⸱ṭhā⸱tab⸱baṁ, "
 "aj"____"aj⸱j’u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so. "
 "ak"____"pa⸱vut⸱tha-jā⸱ti⸱m-ak⸱khī⸱laṁ "
 "am"____"am⸱bho  "
 "an"____"sam⸱pa⸱jā⸱na⸱mu⸱sā⸱vā⸱do kho pa⸱n’ā⸱ya⸱sman⸱to an⸱ta⸱rā⸱yi⸱ko dham⸱mo vut⸱to bha⸱ga⸱va⸱tā.  "
 "ap"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ sik⸱khā⸱sā⸱jī⸱va⸱sa⸱mā⸱pan⸱no sik⸱khaṁ ap⸱pac⸱cak⸱khā⸱ya dub⸱bal⸱yaṁ a⸱nā⸱vi⸱kat⸱vā me⸱thu⸱naṁ dham⸱maṁ pa⸱ṭi⸱se⸱vey⸱ya an⸱ta⸱ma⸱so ti⸱rac⸱chā⸱na⸱ga⸱tā⸱ya⸱’pi; "
 "at"____"tat⸱tha pu⸱ri⸱me⸱su ca⸱tū⸱su kic⸱ce⸱su pa⸱dī⸱pa⸱kic⸱caṁ i⸱dā⸱ni su⸱ri⸱ya⸱lo⸱kas⸱sa at⸱thi⸱tā⸱ya nat⸱thi. "
 "athā"____"ath’ā⸱gū nā⸱bha⸱sā nā⸱gā "
 "añ"____"añ⸱ñat⸱ra a⸱dhi⸱mā⸱nā, "
 "aḍ"____"aḍ⸱ḍha⸱mā⸱so se⸱so gim⸱hā⸱nan⸱’ti, "
 "aṅ"____"hat⸱tha⸱gā⸱haṁ vā ve⸱ṇi⸱gā⸱haṁ vā añ⸱ña⸱ta⸱ras⸱sa vā añ⸱ña⸱ta⸱ras⸱sa vā aṅ⸱gas⸱sa pa⸱rā⸱ma⸱sa⸱naṁ, "
 "aṭ"____"a⸱yaṁ he⸱man⸱to⸱tu a⸱smiñ⸱ca u⸱tum⸱hi aṭ⸱ṭha u⸱po⸱sa⸱thā,  "
 "bad"____"a⸱nu⸱bad⸱dhā (ka. "
 "bal"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ sik⸱khā⸱sā⸱jī⸱va⸱sa⸱mā⸱pan⸱no sik⸱khaṁ ap⸱pac⸱cak⸱khā⸱ya dub⸱bal⸱yaṁ a⸱nā⸱vi⸱kat⸱vā me⸱thu⸱naṁ dham⸱maṁ pa⸱ṭi⸱se⸱vey⸱ya an⸱ta⸱ma⸱so ti⸱rac⸱chā⸱na⸱ga⸱tā⸱ya⸱’pi; "
 "ban"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "bas"____"na⸱vaṁ pa⸱na bhik⸱khu⸱nā san⸱tha⸱taṁ kā⸱rā⸱pet⸱vā chab⸱bas⸱sā⸱ni dhā⸱re⸱tab⸱baṁ. "
 "baṁ"____"u⸱po⸱sa⸱tha⸱ka⸱ra⸱ṇa⸱to pub⸱be  na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ kā⸱tab⸱baṁ ho⸱ti:          "
 "baṅ"____"añ⸱ño at⸱tā dib⸱bo rū⸱pī ma⸱no⸱ma⸱yo sab⸱baṅ⸱ga⸱pac⸱caṅ⸱gī a⸱hī⸱nin⸱dri⸱yo. "
 "baṇ"____"ni⸱sī⸱da⸱na⸱san⸱tha⸱taṁ pa⸱na bhik⸱khu⸱nā kā⸱ra⸱ya⸱mā⸱ne⸱na pu⸱rā⸱ṇa⸱san⸱tha⸱tas⸱sa sā⸱man⸱tā su⸱ga⸱ta⸱vi⸱dat⸱thi ā⸱dā⸱tab⸱bā dub⸱baṇ⸱ṇa⸱ka⸱ra⸱ṇā⸱ya, "
 "bey"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ti⸱kā⸱ya bhik⸱khu⸱ni⸱yā cī⸱va⸱raṁ sib⸱bey⸱ya vā sib⸱bā⸱pey⸱ya vā, "
 "bhab"____"va⸱sī pi⸱tā bhū⸱ta⸱bhab⸱yā⸱naṁ. "
 "bhad"____"rā⸱hu-bhad⸱da⸱m-u⸱pā⸱ga⸱muṁ "
 "bhak"____"na hi sā⸱dhu bha⸱ga⸱va⸱to ab⸱bhak⸱khā⸱naṁ na hi bha⸱ga⸱vā e⸱vaṁ va⸱dey⸱ya. "
 "bhan"____"e⸱vaṁ bhan⸱te).   "
 "bhas"____"saṁ⸱vaṭ⸱ṭa⸱mā⸱ne lo⸱ke ye⸱bhuy⸱ye⸱na sat⸱tā ā⸱bhas⸱sa⸱ra⸱saṁ⸱vat⸱ta⸱ni⸱kā hon⸱ti. "
 "bhat"____"sa⸱ma⸱ṇa⸱bhat⸱ta⸱sa⸱ma⸱yo, "
 "bhañ"____"i⸱ma⸱smiñ⸱ca pa⸱na vey⸱yā⸱ka⸱ra⸱ṇa⸱smiṁ bhañ⸱ña⸱mā⸱ne da⸱sa⸱sa⸱has⸱sī {"
 "bhaṁ"____"te⸱hi bhik⸱khū⸱hi vat⸱thuṁ de⸱se⸱tab⸱baṁ a⸱nā⸱ram⸱bhaṁ sa⸱pa⸱rik⸱ka⸱ma⸱naṁ. "
 "bhaṇ"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ bhaṇ⸱ḍa⸱na⸱jā⸱tā⸱naṁ ka⸱la⸱ha⸱jā⸱tā⸱naṁ vi⸱vā⸱dā⸱pan⸱nā⸱naṁ u⸱pas⸱su⸱tiṁ tiṭ⸱ṭhey⸱ya,  “"
 "bhaṭ"____"sū⸱ra⸱ka⸱thaṁ vi⸱si⸱khā⸱ka⸱thaṁ kum⸱bhaṭ⸱ṭhā⸱na⸱ka⸱thaṁ pub⸱ba⸱pe⸱ta⸱ka⸱thaṁ nā⸱nat⸱ta⸱ka⸱thaṁ lo⸱kak⸱khā⸱yi⸱kaṁ sa⸱mud⸱dak⸱khā⸱yi⸱kaṁ i⸱ti⸱bha⸱vā⸱bha⸱va⸱ka⸱thaṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱ka⸱thā⸱ya pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "bhey"____"ce ū⸱no vī⸱sa⸱ti⸱ga⸱ṇo bhik⸱khu⸱saṅ⸱gho taṁ bhik⸱kuṁ ab⸱bhey⸱ya, "
 "bhik"____"chan⸱dā⸱ra⸱hā⸱naṁ bhik⸱khū⸱naṁ chan⸱dā⸱ha⸱ra⸱ṇañ⸱ca;         "
 "bhikh"____"pa⸱ri⸱vut⸱tha⸱pa⸱ri⸱vā⸱se⸱na bhikh⸱khu⸱nā ut⸱ta⸱riṁ chā⸱rat⸱taṁ bhik⸱khu⸱mā⸱nat⸱tā⸱ya pa⸱ṭi⸱paj⸱ji⸱tab⸱baṁ, "
 "bhin"____"bhik⸱khuṁ pa⸱n’e⸱va ud⸱dis⸱sa u⸱bhin⸱naṁ añ⸱ñā⸱ta⸱kā⸱naṁ ga⸱ha⸱pa⸱tī⸱naṁ vā ga⸱ha⸱pa⸱tā⸱nī⸱naṁ vā pac⸱ce⸱ka⸱cī⸱va⸱ra⸱ce⸱tā⸱pa⸱nā u⸱pak⸱kha⸱ṭā hon⸱ti “i⸱me⸱hi ma⸱yaṁ pac⸱ce⸱ka⸱cī⸱va⸱ra ce⸱tā⸱pa⸱ne⸱hi pac⸱ce⸱ka⸱cī⸱va⸱rā⸱ni ce⸱tā⸱pet⸱vā it⸱than⸱nā⸱maṁ bhik⸱khuṁ cī⸱va⸱re⸱hi ac⸱chā⸱des⸱sā⸱mā”"
 "bhiy"____"ni⸱sin⸱na⸱pub⸱baṁ i⸱mi⸱nā bhik⸱khu⸱nā dvit⸱tik⸱khat⸱tuṁ pā⸱ti⸱mok⸱khe ud⸱dis⸱sa⸱mā⸱ne ko pa⸱na vā⸱do bhiy⸱yo”"
 "bhiñ"____"tañ-ca sab⸱baṁ a⸱bhiñ⸱ñā⸱ya "
 "bhiṁ"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ bhiṁ⸱sā⸱pey⸱ya, "
 "bhog"____"bhik⸱khuṁ pa⸱n’e⸱va ud⸱dis⸱sa rā⸱jā vā rā⸱ja⸱bhog⸱go vā brā⸱ha⸱ma⸱ṇo vā ga⸱ha⸱pa⸱ti⸱ko vā dū⸱te⸱na cī⸱va⸱ra⸱ce⸱tā⸱pa⸱naṁ pa⸱hi⸱ṇey⸱ya, “"
 "bhon"____"ya⸱thā vā pa⸱ne⸱ke bhon⸱to sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā sad⸱dhā⸱dey⸱yā⸱ni bho⸱ja⸱nā⸱ni bhuñ⸱jit⸱vā te e⸱va⸱rū⸱paṁ bī⸱ja⸱gā⸱ma⸱bhū⸱ta⸱gā⸱ma⸱sa⸱mā⸱ram⸱bhaṁ a⸱nu⸱yut⸱tā vi⸱ha⸱ran⸱ti, "
 "bhuc"____"ye⸱hi ta⸱thā⸱ga⸱tas⸱sa ya⸱thā⸱bhuc⸱caṁ vaṇ⸱ṇaṁ sam⸱mā va⸱da⸱mā⸱nā va⸱dey⸱yuṁ. "
 "bhud"____"na⸱mo tas⸱sa bha⸱ga⸱va⸱to a⸱ra⸱ha⸱to sam⸱mā sam⸱bhud⸱dhas⸱sa. ("
 "bhuj"____"ā⸱vā⸱ha⸱naṁ vi⸱vā⸱ha⸱naṁ saṁ⸱va⸱ra⸱ṇaṁ vi⸱va⸱ra⸱ṇaṁ saṁ⸱ki⸱ra⸱ṇaṁ vi⸱ki⸱ra⸱ṇaṁ su⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ dub⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ vi⸱rud⸱dha⸱gab⸱bha⸱ka⸱ra⸱ṇaṁ jiv⸱hā⸱ni⸱ban⸱dha⸱naṁ ha⸱nu⸱saṁ⸱ha⸱na⸱naṁ hat⸱thā⸱bhi⸱jap⸱pa⸱naṁ ha⸱nu⸱jap⸱pa⸱naṁ kaṇ⸱ṇa⸱jap⸱pa⸱naṁ ā⸱dā⸱sa⸱pañ⸱haṁ ku⸱mā⸱ri⸱ka⸱pañ⸱haṁ de⸱va⸱pañ⸱haṁ ā⸱dic⸱cu⸱paṭ⸱ṭhā⸱naṁ ma⸱ha⸱tu⸱paṭ⸱ṭhā⸱naṁ ab⸱bhuj⸱ja⸱la⸱naṁ si⸱riv⸱hā⸱ya⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "bhum"____"yat⸱tha bhum⸱mā ta⸱das⸱si⸱tā "
 "bhun"____"yā⸱va bhik⸱khū bhun⸱jan⸱tī”"
 "bhut"____"yo pa⸱na bhik⸱khu bhut⸱tā⸱vī pa⸱vā⸱ri⸱to a⸱na⸱ti⸱rit⸱taṁ khā⸱da⸱nī⸱yaṁ vā bho⸱ja⸱nī⸱yaṁ vā khā⸱dey⸱ya vā bhuñ⸱jey⸱ya vā, "
 "bhuy"____"ye⸱bhuy⸱ya⸱si⸱kā   6. "
 "bhuñ"____"tā⸱ni pa⸱ṭig⸱ga⸱het⸱vā  sat⸱tā⸱ha⸱pa⸱ra⸱maṁ san⸱ni⸱dhi⸱kā⸱ra⸱kaṁ pa⸱ri⸱bhuñ⸱ji⸱tab⸱bā⸱ni taṁ a⸱tik⸱kā⸱ma⸱ya⸱to, "
 "brah"____"e⸱ta⸱dag⸱gaṁ bha⸱gi⸱ni pā⸱ri⸱ca⸱ri⸱yā⸱naṁ yā mā⸱di⸱saṁ sī⸱la⸱van⸱taṁ kal⸱yā⸱ṇa⸱dham⸱maṁ brah⸱ma⸱cā⸱riṁ e⸱te⸱na dham⸱me⸱na pā⸱ri⸱ca⸱rey⸱yā”"
 "brā"____"bhik⸱khuṁ pa⸱n’e⸱va ud⸱dis⸱sa rā⸱jā vā rā⸱ja⸱bhog⸱go vā brā⸱ha⸱ma⸱ṇo vā ga⸱ha⸱pa⸱ti⸱ko vā dū⸱te⸱na cī⸱va⸱ra⸱ce⸱tā⸱pa⸱naṁ pa⸱hi⸱ṇey⸱ya, “"
 "brāh"____"brāh⸱ma⸱ṇā⸱naṁ, "
 "bud"____"ye ke⸱ci bud⸱dhaṁ sa⸱ra⸱ṇaṁ ga⸱tā⸱se "
 "buṭ"____"dub⸱buṭ⸱ṭhi⸱kā bha⸱vis⸱sa⸱ti, "
 "byat"____"na tā⸱vā⸱haṁ ā⸱vu⸱so e⸱ta⸱smiṁ sik⸱khā⸱pa⸱de sik⸱khis⸱sā⸱mi yā⸱va n’añ⸱ñaṁ bhik⸱khuṁ byat⸱taṁ vi⸱na⸱ya⸱dha⸱raṁ pa⸱ri⸱puc⸱chā⸱mī”"
 "byañ"____"na sū⸱paṁ vā byañ⸱ja⸱naṁ vā o⸱da⸱ne⸱na pa⸱ṭic⸱chā⸱des⸱sā⸱mi bhiy⸱yo⸱kam⸱ya⸱taṁ u⸱pā⸱dā⸱yā⸱’ti, "
 "byā"____"na sa⸱ka⸱va⸱ḷe⸱na mu⸱khe⸱na byā⸱ha⸱ris⸱sā⸱mī⸱’ti,  "
 "caṁ"____"pub⸱ba⸱kic⸱caṁ   "
 "caṅ"____"añ⸱ño at⸱tā dib⸱bo rū⸱pī ma⸱no⸱ma⸱yo sab⸱baṅ⸱ga⸱pac⸱caṅ⸱gī a⸱hī⸱nin⸱dri⸱yo. "
 "caṇ"____"caṇ⸱ḍā⸱laṁ vaṁ⸱saṁ dho⸱va⸱naṁ hat⸱thi⸱yud⸱dhaṁ as⸱sa⸱yud⸱dhaṁ ma⸱hiṁ⸱sa⸱yud⸱dhaṁ {"
 "cey"____"yo pa⸱na bhik⸱khu a⸱nu⸱pa⸱sam⸱pan⸱naṁ pa⸱da⸱so dham⸱maṁ vā⸱cey⸱ya, "
 "chaḍ"____"na sa⸱sit⸱tha⸱kaṁ pat⸱ta⸱dho⸱va⸱naṁ an⸱ta⸱ra⸱gha⸱re chaḍ⸱ḍes⸱sā⸱mī⸱’ti, "
 "chaṁ"____"tuc⸱chaṁ mu⸱sā vi⸱la⸱pin”"
 "chey"____"a⸱nā⸱puc⸱chaṁ vā gac⸱chey⸱ya, "
 "chuṁ"____"nā⸱man⸱va⸱ye⸱na ā⸱gañ⸱chuṁ "
 "ciṅ"____"aṭ⸱ṭha⸱pa⸱daṁ da⸱sa⸱pa⸱daṁ ā⸱kā⸱saṁ pa⸱ri⸱hā⸱ra⸱pa⸱thaṁ san⸱ti⸱kaṁ kha⸱li⸱kaṁ gha⸱ṭi⸱kaṁ sa⸱lā⸱ka⸱hat⸱thaṁ ak⸱khaṁ paṅ⸱ga⸱cī⸱raṁ vaṅ⸱ka⸱kaṁ mok⸱kha⸱ci⸱kaṁ ciṅ⸱gu⸱li⸱kaṁ {"
 "ciṇ"____"ciṇ⸱ṇa⸱mā⸱nat⸱to bhik⸱khu, "
 "cuṁ"____"e⸱vaṁ vut⸱te te bhik⸱khū bha⸱ga⸱van⸱taṁ e⸱ta⸱da⸱vo⸱cuṁ — “"
 "cuṇ"____"mu⸱kha⸱cuṇ⸱ṇaṁ mu⸱kha⸱le⸱pa⸱naṁ hat⸱tha⸱ban⸱dhaṁ si⸱khā⸱ban⸱dhaṁ daṇ⸱ḍaṁ nā⸱ḷi⸱kaṁ a⸱siṁ {"
 "dab"____"aṅ⸱gaṁ ni⸱mit⸱taṁ up⸱pā⸱taṁ su⸱pi⸱naṁ lak⸱kha⸱ṇaṁ mū⸱si⸱kac⸱chin⸱naṁ ag⸱gi⸱ho⸱maṁ dab⸱bi⸱ho⸱maṁ thu⸱sa⸱ho⸱maṁ ka⸱ṇa⸱ho⸱maṁ taṇ⸱ḍu⸱la⸱ho⸱maṁ sap⸱pi⸱ho⸱maṁ te⸱la⸱ho⸱maṁ mu⸱kha⸱ho⸱maṁ lo⸱hi⸱ta⸱ho⸱maṁ aṅ⸱ga⸱vij⸱jā vat⸱thu⸱vij⸱jā khat⸱ta⸱vij⸱jā {"
 "dad"____"dad⸱dal⸱la⸱mā⸱nā aṭ⸱ṭhaṁ⸱su "
 "dag"____"e⸱ta⸱dag⸱gaṁ bha⸱gi⸱ni pā⸱ri⸱ca⸱ri⸱yā⸱naṁ yā mā⸱di⸱saṁ sī⸱la⸱van⸱taṁ kal⸱yā⸱ṇa⸱dham⸱maṁ brah⸱ma⸱cā⸱riṁ e⸱te⸱na dham⸱me⸱na pā⸱ri⸱ca⸱rey⸱yā”"
 "daj"____"ap⸱p’e⸱va nā⸱ma ma⸱yam⸱’pi ā⸱ya⸱sman⸱tā⸱naṁ kiñ⸱ci⸱mat⸱taṁ a⸱nu⸱pa⸱daj⸱jey⸱yā⸱mā”"
 "dak"____"dak⸱khi⸱tā⸱ye⸱va a⸱pa⸱rā⸱ji⸱ta-saṅ⸱ghan⸱ti.”  "
 "dal"____"dad⸱dal⸱la⸱mā⸱nā aṭ⸱ṭhaṁ⸱su "
 "dan"____"ā⸱mi⸱sa⸱he⸱tu bhik⸱khū bhik⸱khu⸱ni⸱yo o⸱va⸱dan⸱tī”"
 "dap"____"ca⸱ra vā⸱dap⸱pa⸱mok⸱khā⸱ya, "
 "das"____"sam⸱pa⸱jā⸱na⸱mu⸱sā⸱vā⸱das⸱sa ho⸱ti. "
 "dat"____"dī⸱gha⸱so dvā⸱da⸱sa vi⸱dat⸱thi⸱yo su⸱ga⸱ta⸱vi⸱dat⸱thi⸱yā ti⸱ri⸱yaṁ satt’ an⸱ta⸱rā. "
 "dañ"____"chan⸱dañ⸱ca ru⸱ciñ⸱ca ā⸱dā⸱ya vo⸱ha⸱ra⸱ti, "
 "daṁ"____"tatr’ i⸱daṁ pa⸱mā⸱naṁ. "
 "daṇ"____"na daṇ⸱ḍa⸱pā⸱ṇis⸱sa a⸱gi⸱lā⸱nas⸱sa dham⸱maṁ de⸱sis⸱sā⸱mī⸱’ti, "
 "daṭ"____"ya⸱thā vā pa⸱ne⸱ke bhon⸱to sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā sad⸱dhā⸱dey⸱yā⸱ni bho⸱ja⸱nā⸱ni bhuñ⸱jit⸱vā te e⸱va⸱rū⸱paṁ jū⸱tap⸱pa⸱mā⸱daṭ⸱ṭhā⸱nā⸱nu⸱yo⸱gaṁ a⸱nu⸱yut⸱tā vi⸱ha⸱ran⸱ti, "
 "des"____"i⸱mi⸱nā cī⸱va⸱ra⸱ce⸱tā⸱pa⸱ne⸱na cī⸱va⸱raṁ ce⸱tā⸱pet⸱vā it⸱than⸱nā⸱maṁ bhik⸱khuṁ cī⸱va⸱re⸱na ac⸱chā⸱des⸱sā⸱mī”"
 "det"____"a⸱tha kho tā de⸱va⸱tā bha⸱ga⸱van⸱taṁ a⸱bhi⸱vā⸱det⸱vā e⸱ka⸱m-an⸱taṁ aṭ⸱ṭhaṁ⸱su. "
 "dey"____"ta⸱to a⸱pa⸱re⸱na sa⸱ma⸱ye⸱na sa⸱ma⸱nug⸱gā⸱hi⸱ya⸱mā⸱no vā a⸱sa⸱ma⸱nug⸱gā⸱hi⸱ya⸱mā⸱no vā ā⸱pan⸱no vi⸱sud⸱dhā⸱pek⸱kho e⸱vaṁ va⸱dey⸱ya, “"
 "dhab"____"gan⸱dhab⸱bā⸱naṁ ā⸱dhi⸱pa⸱ti "
 "dham"____"sam⸱pa⸱jā⸱na⸱mu⸱sā⸱vā⸱do kho pa⸱n’ā⸱ya⸱sman⸱to an⸱ta⸱rā⸱yi⸱ko dham⸱mo vut⸱to bha⸱ga⸱va⸱tā.  "
 "dhas"____"na⸱mo tas⸱sa bha⸱ga⸱va⸱to a⸱ra⸱ha⸱to sam⸱mā sam⸱bhud⸱dhas⸱sa. ("
 "dhañ"____"ā⸱ma⸱ka⸱dhañ⸱ña⸱pa⸱ṭig⸱ga⸱ha⸱ṇā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo....  ♦ "
 "dhaṁ"____"u⸱po⸱sa⸱tha⸱ka⸱ra⸱ṇa⸱to pub⸱be  na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ kā⸱tab⸱baṁ ho⸱ti:          "
 "dhey"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "dhic"____"a⸱dhic⸱ca⸱sa⸱mup⸱pan⸱na⸱vā⸱do (dn 1) ♦ 67. “"
 "dhiṁ"____"pā⸱ri⸱sud⸱dhiṁ ā⸱ya⸱sman⸱to ā⸱ro⸱ce⸱tha, "
 "dhiṭ"____"ma⸱hal⸱la⸱kaṁ pa⸱na bhik⸱khu⸱nā vi⸱hā⸱raṁ kā⸱ra⸱ya⸱mā⸱ne⸱na yā⸱va dvā⸱ra⸱ko⸱sā ag⸱ga⸱laṭ⸱ṭha⸱pa⸱nā⸱ya ā⸱lo⸱ka⸱san⸱dhi⸱pa⸱ri⸱kam⸱mā⸱ya dvit⸱tic⸱cha⸱da⸱nas⸱sa pa⸱ri⸱yā⸱yaṁ ap⸱pa⸱ha⸱ri⸱te ṭhi⸱te⸱na a⸱dhiṭ⸱ṭhā⸱tab⸱baṁ, "
 "dib"____"dib⸱bā di⸱jā pak⸱khi vi⸱sud⸱dha-cak⸱khū "
 "dic"____"ā⸱vā⸱ha⸱naṁ vi⸱vā⸱ha⸱naṁ saṁ⸱va⸱ra⸱ṇaṁ vi⸱va⸱ra⸱ṇaṁ saṁ⸱ki⸱ra⸱ṇaṁ vi⸱ki⸱ra⸱ṇaṁ su⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ dub⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ vi⸱rud⸱dha⸱gab⸱bha⸱ka⸱ra⸱ṇaṁ jiv⸱hā⸱ni⸱ban⸱dha⸱naṁ ha⸱nu⸱saṁ⸱ha⸱na⸱naṁ hat⸱thā⸱bhi⸱jap⸱pa⸱naṁ ha⸱nu⸱jap⸱pa⸱naṁ kaṇ⸱ṇa⸱jap⸱pa⸱naṁ ā⸱dā⸱sa⸱pañ⸱haṁ ku⸱mā⸱ri⸱ka⸱pañ⸱haṁ de⸱va⸱pañ⸱haṁ ā⸱dic⸱cu⸱paṭ⸱ṭhā⸱naṁ ma⸱ha⸱tu⸱paṭ⸱ṭhā⸱naṁ ab⸱bhuj⸱ja⸱la⸱naṁ si⸱riv⸱hā⸱ya⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "din"____"yo pa⸱na bhik⸱khu gā⸱mā vā a⸱rañ⸱ñā vā a⸱din⸱naṁ they⸱ya⸱saṅ⸱khā⸱taṁ ā⸱di⸱yey⸱ya, "
 "dis"____"tuṇ⸱hī bhā⸱ve⸱na kho pa⸱n’ā⸱ya⸱sman⸱te pa⸱ri⸱sud⸱dhā⸱’ti ve⸱dis⸱sā⸱mi. "
 "dit"____"u⸱po⸱sa⸱tha⸱kam⸱mas⸱sa pat⸱ta⸱kal⸱lat⸱taṁ vi⸱dit⸱vā i⸱dā⸱ni ka⸱ri⸱ya⸱mā⸱no u⸱po⸱sa⸱tho saṅ⸱ghe⸱na a⸱nu⸱mā⸱ne⸱tab⸱bo. ("
 "diṁ"____"kaṇ⸱ḍu⸱pa⸱ṭic⸱chā⸱diṁ pa⸱na bhik⸱khu⸱nā kā⸱ra⸱ya⸱mā⸱ne⸱na pa⸱mā⸱ṇi⸱kā kā⸱re⸱tab⸱bā; "
 "diṭ"____"ud⸱diṭ⸱ṭhā kho ā⸱ya⸱sman⸱to cat⸱tā⸱ro pā⸱rā⸱ji⸱kā dham⸱mā, "
 "dn"____"cū⸱ḷa⸱sī⸱laṁ (dn 1) ♦ 7. “"
 "dri"____"in⸱dri⸱yā⸱ni rak⸱khan⸱ti paṇ⸱ḍi⸱tā⸱ti.”  "
 "dub"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ sik⸱khā⸱sā⸱jī⸱va⸱sa⸱mā⸱pan⸱no sik⸱khaṁ ap⸱pac⸱cak⸱khā⸱ya dub⸱bal⸱yaṁ a⸱nā⸱vi⸱kat⸱vā me⸱thu⸱naṁ dham⸱maṁ pa⸱ṭi⸱se⸱vey⸱ya an⸱ta⸱ma⸱so ti⸱rac⸱chā⸱na⸱ga⸱tā⸱ya⸱’pi; "
 "dud"____"de⸱va⸱dud⸱ra⸱bhi {"
 "duj"____"pu⸱ri⸱sa kiṁ tuyh’ i⸱mi⸱nā pā⸱pa⸱ke⸱na duj⸱jī⸱vi⸱te⸱na? "
 "duk"____"a⸱mut⸱rā⸱siṁ e⸱vaṁ⸱nā⸱mo e⸱vaṁ⸱got⸱to e⸱vaṁ⸱vaṇ⸱ṇo e⸱va⸱mā⸱hā⸱ro e⸱vaṁ⸱su⸱kha⸱duk⸱khap⸱pa⸱ṭi⸱saṁ⸱ve⸱dī e⸱va⸱mā⸱yu⸱pa⸱ri⸱yan⸱to, "
 "dul"____"tas⸱sa te dul⸱lad⸱dhaṁ. "
 "dun"____"de⸱va⸱dun⸱du⸱bhi (syā. "
 "duṭ"____"yo pa⸱na bhik⸱khu o⸱tiṇ⸱ṇo vi⸱pa⸱ri⸱ṇa⸱te⸱na cit⸱te⸱na mā⸱tu⸱gā⸱maṁ duṭ⸱ṭhul⸱lā⸱hi vā⸱cā⸱hi o⸱bhā⸱sey⸱ya. "
 "dve"____"dve u⸱po⸱sa⸱thā a⸱tik⸱kan⸱tā          "
 "dvi"____"dvi⸱rat⸱ta⸱ti⸱rat⸱taṁ te⸱na bhik⸱khu⸱nā se⸱nā⸱ya va⸱si⸱tab⸱baṁ. "
 "dvin"____"tam⸱’ e⸱naṁ sad⸱dhey⸱ya⸱va⸱ca⸱sā u⸱pā⸱si⸱kā dis⸱vā dvin⸱naṁ dham⸱mā⸱naṁ añ⸱ña⸱ta⸱re⸱na va⸱dey⸱ya saṅ⸱ghā⸱di⸱se⸱se⸱na vā pā⸱cit⸱ti⸱ye⸱na vā. "
 "dvit"____"ci⸱va⸱rat⸱thi⸱ke⸱na bhik⸱kha⸱ve bhik⸱khu⸱nā vey⸱yā⸱vac⸱ca⸱ka⸱ro u⸱pa⸱saṅ⸱ka⸱mit⸱vā dvit⸱tik⸱khat⸱tuṁ co⸱de⸱tab⸱bo sā⸱re⸱tab⸱bo “at⸱tho me ā⸱vu⸱so cī⸱va⸱re⸱nā”"
 "dvā"____"dī⸱gha⸱so dvā⸱da⸱sa vi⸱dat⸱thi⸱yo su⸱ga⸱ta⸱vi⸱dat⸱thi⸱yā ti⸱ri⸱yaṁ satt’ an⸱ta⸱rā. "
 "dvī"____"e⸱ke sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā a⸱dhic⸱ca⸱sa⸱mup⸱pan⸱ni⸱kā a⸱dhic⸱ca⸱sa⸱mup⸱pan⸱naṁ at⸱tā⸱nañ⸱ca lo⸱kañ⸱ca pañ⸱ña⸱pen⸱ti dvī⸱hi vat⸱thū⸱hi. "
 "ed"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "el"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "et"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "etth"____"pa⸱ri⸱suddh’ etth’ ā⸱ya⸱sman⸱to, "
 "gacch"____"tas⸱sa dā⸱pet⸱vā vā a⸱dā⸱pet⸱vā vā uy⸱yo⸱jey⸱ya “gacch’ ā⸱vu⸱so, "
 "gam"____"añ⸱ñe⸱va dham⸱mā gam⸱bhī⸱rā dud⸱da⸱sā du⸱ra⸱nu⸱bo⸱dhā san⸱tā pa⸱ṇī⸱tā a⸱tak⸱kā⸱va⸱ca⸱rā ni⸱pu⸱ṇā paṇ⸱ḍi⸱ta⸱ve⸱da⸱nī⸱yā, "
 "gay"____"yo pa⸱na bhik⸱khu sa⸱mag⸱gas⸱sa saṅ⸱ghas⸱sa bhe⸱dā⸱ya pa⸱rak⸱ka⸱mey⸱ya bhe⸱da⸱na⸱saṁ⸱vat⸱ta⸱ni⸱kaṁ vā a⸱dhi⸱ka⸱ra⸱ṇaṁ sa⸱mā⸱dā⸱ya pag⸱gay⸱ha tiṭ⸱ṭhey⸱ya, "
 "gaṁ"____"yo pa⸱na bhik⸱khu o⸱tiṇ⸱ṇo vi⸱pa⸱ri⸱ṇa⸱te⸱na cit⸱te⸱na mā⸱tu⸱gā⸱me⸱na sad⸱dhiṁ kā⸱ya⸱saṁ⸱sag⸱gaṁ sa⸱mā⸱paj⸱jey⸱ya, "
 "gaṇ"____"e⸱vañ⸱ca so bhik⸱khu bhik⸱khū⸱hi vuc⸱ca⸱mā⸱no tath’e⸱va pag⸱gaṇ⸱hey⸱ya, "
 "ghaṁ"____"chet⸱vā khī⸱laṁ chet⸱vā pa⸱lī⸱ghaṁ "
 "ghaṇ"____"kin⸱nu⸱ghaṇ⸱ḍu ni⸱ghaṇ⸱ḍu ca "
 "giṁ"____"lā⸱bhe⸱na lā⸱bhaṁ ni⸱ji⸱giṁ bhi⸱tā⸱ro (sī. "
 "guṇ"____"na o⸱guṇ⸱ṭhi⸱to an⸱ta⸱ra⸱gha⸱re ga⸱mis⸱sā⸱mī⸱’ti,  "
 "gīṁ"____"lā⸱bhe⸱na lā⸱bhaṁ ni⸱ji⸱gīṁ⸱si⸱tā⸱ro ca {"
 "hab"____"in⸱da-nā⸱mā ma⸱hab⸱ba⸱lā "
 "hac"____"yo pa⸱na bhik⸱khu saṅ⸱ghi⸱ke vi⸱hā⸱re u⸱pa⸱ri⸱ve⸱hā⸱sa⸱ku⸱ṭi⸱yā ā⸱hac⸱ca⸱pā⸱da⸱kaṁ mañ⸱caṁ vā pī⸱ṭhaṁ vā a⸱bhi⸱ni⸱sī⸱dey⸱ya vā a⸱bhi⸱ni⸱paj⸱jey⸱ya vā, "
 "hal"____"ma⸱hal⸱la⸱kaṁ pa⸱na bhik⸱khu⸱nā vi⸱hā⸱raṁ kā⸱ra⸱ya⸱mā⸱ne⸱na sas⸱sā⸱mi⸱kaṁ at⸱tud⸱de⸱saṁ bhik⸱khū a⸱bhi⸱ne⸱tab⸱bā vat⸱thu⸱de⸱sa⸱nā⸱ya, "
 "hamp"____"a⸱hamp’ ā⸱ya⸱sman⸱te na kiñ⸱ci vak⸱khā⸱mi kal⸱yā⸱ṇaṁ vā pā⸱pa⸱kaṁ vā, "
 "han"____"han⸱da bhik⸱ku khā⸱da vā bhuñ⸱ja vā”"
 "has"____"u⸱da⸱ke has⸱sa⸱dham⸱me pā⸱cit⸱ti⸱yaṁ.    54. "
 "hat"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "hañ"____"a⸱hañ⸱hi ā⸱tap⸱pa⸱man⸱vā⸱ya pa⸱dhā⸱na⸱man⸱vā⸱ya a⸱nu⸱yo⸱ga⸱man⸱vā⸱ya ap⸱pa⸱mā⸱da⸱man⸱vā⸱ya sam⸱mā⸱ma⸱na⸱si⸱kā⸱ra⸱man⸱vā⸱ya ta⸱thā⸱rū⸱paṁ ce⸱to⸱sa⸱mā⸱dhiṁ phu⸱sā⸱mi, "
 "haṁ"____"yo pa⸱na bhik⸱khu sañ⸱cic⸱ca ma⸱nus⸱sa⸱vig⸱ga⸱haṁ jī⸱vi⸱tā vo⸱ro⸱pey⸱ya,  "
 "haṭ"____"tañ⸱ce añ⸱ñā⸱ta⸱ko ga⸱ha⸱pa⸱ti vā ga⸱ha⸱pa⸱tā⸱nī vā ba⸱hū⸱hi cī⸱va⸱re⸱hi a⸱bhi⸱haṭ⸱ṭhuṁ pa⸱vā⸱rey⸱ya, "
 "hes"____"sak⸱kac⸱caṁ piṇ⸱ḍa⸱pā⸱taṁ pa⸱ṭig⸱ga⸱hes⸱sā⸱mī⸱’ti,  "
 "het"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "hey"____"e⸱vañ⸱ca so bhik⸱khu bhik⸱khū⸱hi vuc⸱ca⸱mā⸱no tath’e⸱va pag⸱gaṇ⸱hey⸱ya, "
 "hid"____"nat⸱thi i⸱to ba⸱hid⸱dhā.  ♦ 36. “"
 "hikh"____"mā ā⸱ya⸱sman⸱to e⸱taṁ hikh⸱huṁ kiñ⸱ci a⸱va⸱cut⸱tha, "
 "his"____"ā⸱vi⸱ka⸱tā his⸱sa phā⸱su ho⸱ti. ("
 "hit"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "hiṁ"____"caṇ⸱ḍā⸱laṁ vaṁ⸱saṁ dho⸱va⸱naṁ hat⸱thi⸱yud⸱dhaṁ as⸱sa⸱yud⸱dhaṁ ma⸱hiṁ⸱sa⸱yud⸱dhaṁ {"
 "hon"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "hum"____"ye pa⸱na ma⸱yaṁ a⸱hum⸱hā te⸱na bho⸱tā brah⸱mu⸱nā nim⸱mi⸱tā, "
 "hup"____"na bā⸱hup⸱pa⸱cā⸱la⸱kaṁ an⸱ta⸱ra⸱gha⸱re ga⸱mis⸱sā⸱mī⸱’ti, "
 "hut"____"i⸱ti⸱’ssa mu⸱hut⸱tam⸱’pi a⸱phā⸱su bha⸱vis⸱sa⸱tī”"
 "huṁ"____"mā ā⸱ya⸱sman⸱to e⸱taṁ hikh⸱huṁ kiñ⸱ci a⸱va⸱cut⸱tha, "
 "hāb"____"a⸱ha⸱ma⸱smi brah⸱mā ma⸱hāb⸱rah⸱mā a⸱bhi⸱bhū a⸱na⸱bhi⸱bhū⸱to añ⸱ña⸱dat⸱thu⸱da⸱so va⸱sa⸱vat⸱tī is⸱sa⸱ro kat⸱tā nim⸱mā⸱tā seṭ⸱ṭho sa⸱ji⸱tā {"
 "ic"____"yā⸱va⸱ta⸱ti⸱yañ⸱’ce sa⸱ma⸱nu⸱bhā⸱si⸱ya⸱mā⸱no taṁ pa⸱ṭi⸱nis⸱saj⸱jey⸱ya ic⸱c’e⸱taṁ ku⸱sa⸱laṁ. "
 "id"____"id⸱dhi⸱man⸱to ju⸱ti⸱man⸱to "
 "in"____"yo pa⸱na bhik⸱khu rañ⸱ño khat⸱ti⸱yas⸱sa mud⸱dhā⸱bhi⸱sit⸱tas⸱sa a⸱nik⸱khan⸱ta⸱rā⸱ja⸱ke a⸱nig⸱ga⸱ta⸱ra⸱ta⸱na⸱ke pub⸱be ap⸱pa⸱ṭi⸱saṁ⸱vi⸱di⸱to in⸱da⸱khī⸱laṁ a⸱tik⸱ka⸱mey⸱ya, "
 "is"____"da⸱s’et⸱tha is⸱sa⸱rā ā⸱gū "
 "it"____"yo pa⸱na bhik⸱khu sañ⸱ca⸱rit⸱taṁ sa⸱mā⸱paj⸱jey⸱ya it⸱thi⸱yā vā pu⸱ri⸱sa⸱ma⸱tiṁ pu⸱ri⸱sas⸱sa vā it⸱thī⸱ma⸱tiṁ jā⸱yat⸱ta⸱ne vā jā⸱rat⸱ta⸱ne vā an⸱ta⸱ma⸱so taṁ kha⸱ṇi⸱kā⸱ya⸱’ pi, "
 "iv"____"iv. "
 "iñ"____"ne⸱saṁ lo⸱mam-pi iñ⸱ja⸱yuṁ. "
 "jaṁ"____"yo pa⸱na bhik⸱khu mā⸱tu⸱gā⸱me⸱na sad⸱dhiṁ e⸱ko e⸱kā⸱ya ra⸱ho pa⸱ṭic⸱chan⸱ne ā⸱sa⸱ne a⸱laṁ⸱kam⸱ma⸱ni⸱ye ni⸱saj⸱jaṁ kap⸱pey⸱ya. "
 "jey"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "jiṁ"____"gā⸱ray⸱haṁ ā⸱vu⸱so dham⸱maṁ ā⸱paj⸱jiṁ a⸱sap⸱pā⸱yaṁ, "
 "kaḍ"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ ku⸱pi⸱to a⸱nat⸱ta⸱ma⸱no saṅ⸱ghi⸱kā vi⸱hā⸱rā nik⸱kaḍ⸱ḍhey⸱ya vā nik⸱kaḍ⸱ḍhā⸱pey⸱ya vā, "
 "kaṁ"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "kaṅ"____"ā⸱kaṅ⸱kha⸱mā⸱ne⸱na bhik⸱khu⸱nā  "
 "kaṇ"____"ā⸱kaṇ⸱kha⸱mā⸱ne⸱na bhik⸱khu⸱nā dvit⸱ti⸱pat⸱ta⸱pū⸱rā pa⸱ṭig⸱ga⸱he⸱tab⸱bā. "
 "khaṁ"____"bhik⸱khu⸱pā⸱ṭi⸱mok⸱khaṁ   "
 "khiy"____"uj⸱jhā⸱pa⸱na⸱ke khiy⸱ya⸱na⸱ke pā⸱cit⸱ti⸱yaṁ.    14. "
 "khiḍ"____"khiḍ⸱ḍā-pa⸱dū⸱si⸱kā ā⸱gū "
 "khuṁ"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ duṭ⸱ṭho do⸱so ap⸱pa⸱tī⸱to a⸱mū⸱la⸱ke⸱na pā⸱rā⸱ji⸱ke⸱na dham⸱me⸱na a⸱nud⸱dhaṁ⸱sey⸱ya,  “"
 "kiṁ"____"kiṁ saṅ⸱ghas⸱sa pub⸱ba⸱kic⸱caṁ?  "
 "kiṇ"____"ta⸱yo pa⸱kiṇ⸱ṇa⸱kā   "
 "kuṁ"____"ce ū⸱no vī⸱sa⸱ti⸱ga⸱ṇo bhik⸱khu⸱saṅ⸱gho taṁ bhik⸱kuṁ ab⸱bhey⸱ya, "
 "lad"____"tas⸱sa te dul⸱lad⸱dhaṁ. "
 "lag"____"dvi⸱rat⸱ta⸱ti⸱rat⸱tañ⸱ce bhik⸱khu se⸱nā⸱ya va⸱sa⸱mā⸱no uy⸱yo⸱dhi⸱kaṁ vā ba⸱lag⸱gaṁ vā se⸱nāb⸱yū⸱haṁ vā a⸱nī⸱ka⸱das⸱sa⸱naṁ vā gac⸱chey⸱ya, "
 "laj"____"laj⸱jī, "
 "lak"____"e⸱van⸱taṁ u⸱po⸱sa⸱tha⸱kam⸱maṁ i⸱me⸱hi ca⸱tū⸱hi  lak⸱kha⸱ṇe⸱hi saṅ⸱ga⸱hi⸱taṁ pat⸱ta⸱kal⸱laṁ nā⸱ma ho⸱ti, "
 "lam"____"lam⸱bi⸱ta⸱kā lā⸱ma⸱seṭ⸱ṭhā "
 "lan"____"a⸱lan⸱’te i⸱dha vā⸱se⸱nā” "
 "las"____"yo pa⸱na bhik⸱khu jā⸱naṁ saṅ⸱ghi⸱kaṁ lā⸱bhaṁ pa⸱ri⸱ṇa⸱taṁ pug⸱ga⸱las⸱sa pa⸱ri⸱ṇā⸱mey⸱ya, "
 "lat"____"u⸱po⸱sa⸱tha⸱kam⸱mas⸱sa pat⸱ta⸱kal⸱lat⸱taṁ vi⸱dit⸱vā i⸱dā⸱ni ka⸱ri⸱ya⸱mā⸱no u⸱po⸱sa⸱tho saṅ⸱ghe⸱na a⸱nu⸱mā⸱ne⸱tab⸱bo. ("
 "lañ"____"a⸱lañ⸱ca kho ho⸱ti mā⸱tu⸱gā⸱maṁ duṭ⸱ṭhul⸱lā⸱hi vā⸱cā⸱hi o⸱bhā⸱si⸱uṁ. "
 "laṁ"____"e⸱van⸱taṁ u⸱po⸱sa⸱tha⸱kam⸱maṁ i⸱me⸱hi ca⸱tū⸱hi  lak⸱kha⸱ṇe⸱hi saṅ⸱ga⸱hi⸱taṁ pat⸱ta⸱kal⸱laṁ nā⸱ma ho⸱ti, "
 "laṅ"____"ā⸱san⸱diṁ pal⸱laṅ⸱kaṁ go⸱na⸱kaṁ cit⸱ta⸱kaṁ pa⸱ṭi⸱kaṁ pa⸱ṭa⸱li⸱kaṁ tū⸱li⸱kaṁ vi⸱ka⸱ti⸱kaṁ ud⸱da⸱lo⸱miṁ e⸱kan⸱ta⸱lo⸱miṁ kaṭ⸱ṭis⸱saṁ ko⸱sey⸱yaṁ kut⸱ta⸱kaṁ hat⸱that⸱tha⸱raṁ as⸱sat⸱tha⸱raṁ ra⸱that⸱tha⸱raṁ {"
 "laṭ"____"ma⸱hal⸱la⸱kaṁ pa⸱na bhik⸱khu⸱nā vi⸱hā⸱raṁ kā⸱ra⸱ya⸱mā⸱ne⸱na yā⸱va dvā⸱ra⸱ko⸱sā ag⸱ga⸱laṭ⸱ṭha⸱pa⸱nā⸱ya ā⸱lo⸱ka⸱san⸱dhi⸱pa⸱ri⸱kam⸱mā⸱ya dvit⸱tic⸱cha⸱da⸱nas⸱sa pa⸱ri⸱yā⸱yaṁ ap⸱pa⸱ha⸱ri⸱te ṭhi⸱te⸱na a⸱dhiṭ⸱ṭhā⸱tab⸱baṁ, "
 "lek"____"i⸱daṁ kho ā⸱vu⸱so ci⸱va⸱raṁ maṁ ud⸱dis⸱sa vī⸱ya⸱ti ā⸱ya⸱tañ⸱ca ka⸱ro⸱tha vit⸱tha⸱tañ⸱ca ap⸱pi⸱tañ⸱ca su⸱vi⸱tañ⸱ca su⸱pa⸱vā⸱yi⸱tañ⸱ca su⸱vi⸱lek⸱khi⸱tañ⸱ca su⸱vi⸱tac⸱chi⸱tañ⸱ca ka⸱ro⸱tha; "
 "let"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "ley"____"sū⸱ley⸱ya-ru⸱ci⸱rā ā⸱gū "
 "lik"____"te tat⸱tha hon⸱ti ma⸱no⸱ma⸱yā pī⸱ti⸱bhak⸱khā sa⸱yaṁ⸱pa⸱bhā an⸱ta⸱lik⸱kha⸱ca⸱rā su⸱bhaṭ⸱ṭhā⸱yi⸱no, "
 "liṁ"____"san⸱nay⸱hit⸱vā ba⸱liṁ se⸱naṁ "
 "mac"____"mac⸱cho, "
 "mad"____"na thū⸱pa⸱to o⸱mad⸱dit⸱vā piṇ⸱ḍa⸱pā⸱taṁ bhuñ⸱jis⸱sā⸱mī⸱’ti, "
 "mag"____"sa⸱ce so di⸱va⸱so cā⸱tud⸱da⸱si-paṇ⸱ṇa⸱ra⸱sī sā⸱mag⸱gī⸱na⸱mañ⸱ña⸱ta⸱ro ya⸱thāj⸱ja u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so,   "
 "maj"____"taṇ⸱ṭhā⸱na⸱sam⸱maj⸱ja⸱nañ⸱ca;         "
 "mam"____"ap⸱p’e⸱va nā⸱ma naṁ i⸱mam⸱hā brah⸱ma⸱ca⸱ri⸱yā cā⸱vey⸱yan” "
 "man"____"u⸱tū⸱nī⸱dha pa⸱na sā⸱sa⸱ne he⸱man⸱ta-gim⸱ha-vas⸱sā⸱nā⸱naṁ va⸱se⸱na tī⸱ṇi hon⸱ti.   "
 "map"____"yā⸱va⸱ti⸱kā ca bhik⸱khu kam⸱map⸱pat⸱tā  saṅ⸱ghu⸱po⸱sa⸱thā⸱ra⸱hā cat⸱tā⸱ro vā ta⸱to vā a⸱ti⸱re⸱kā pa⸱ka⸱tat⸱tā pā⸱rā⸱ji⸱kaṁ a⸱nā⸱pan⸱nā saṅ⸱ghe⸱na vā a⸱nuk⸱khit⸱tā, "
 "mas"____"u⸱po⸱sa⸱tha⸱kam⸱mas⸱sa pat⸱ta⸱kal⸱lat⸱taṁ vi⸱dit⸱vā i⸱dā⸱ni ka⸱ri⸱ya⸱mā⸱no u⸱po⸱sa⸱tho saṅ⸱ghe⸱na a⸱nu⸱mā⸱ne⸱tab⸱bo. ("
 "mat"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ duṭ⸱ṭho do⸱so ap⸱pa⸱tī⸱to añ⸱ña⸱bhā⸱gi⸱yas⸱sa a⸱dhi⸱ka⸱ra⸱ṇas⸱sa kiñ⸱ci de⸱saṁ le⸱sa⸱mat⸱taṁ u⸱pā⸱dā⸱ya pā⸱rā⸱ji⸱ke⸱na dham⸱me⸱na a⸱nud⸱dhaṁ⸱sey⸱ya, “"
 "may"____"sey⸱ya⸱thā⸱pi may⸱haṁ e⸱ta⸱ra⸱hi. "
 "mañ"____"sa⸱ce so di⸱va⸱so cā⸱tud⸱da⸱si-paṇ⸱ṇa⸱ra⸱sī sā⸱mag⸱gī⸱na⸱mañ⸱ña⸱ta⸱ro ya⸱thāj⸱ja u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so,   "
 "maṁ"____"e⸱van⸱taṁ u⸱po⸱sa⸱tha⸱kam⸱maṁ i⸱me⸱hi ca⸱tū⸱hi  lak⸱kha⸱ṇe⸱hi saṅ⸱ga⸱hi⸱taṁ pat⸱ta⸱kal⸱laṁ nā⸱ma ho⸱ti, "
 "maṅ"____"a⸱yaṁ at⸱tā pañ⸱ca⸱hi kā⸱ma⸱gu⸱ṇe⸱hi sa⸱map⸱pi⸱to sa⸱maṅ⸱gī⸱bhū⸱to pa⸱ri⸱cā⸱re⸱ti, "
 "maṇ"____"pa⸱ri⸱maṇ⸱ḍa⸱laṁ ni⸱vā⸱ses⸱sā⸱mī⸱’ti, "
 "maṭ"____"i⸱me diṭ⸱ṭhiṭ⸱ṭhā⸱nā e⸱vaṁ⸱ga⸱hi⸱tā e⸱vaṁ⸱pa⸱rā⸱maṭ⸱ṭhā e⸱vaṁ⸱ga⸱ti⸱kā bha⸱van⸱ti e⸱vaṁa⸱bhi⸱sam⸱pa⸱rā⸱yā⸱’ti, "
 "men"____"yo pa⸱na bhik⸱khu sa⸱mag⸱ge⸱na saṅ⸱ghe⸱na cī⸱va⸱raṁ dat⸱vā pac⸱chā khiy⸱ya⸱na⸱dham⸱maṁ ā⸱paj⸱jey⸱ya “ya⸱thā⸱san⸱thu⸱taṁ bhik⸱khū saṅ⸱ghi⸱kaṁ lā⸱bhaṁ pa⸱ri⸱ṇā⸱men⸱tī”"
 "ment"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "mes"____"thre⸱e ti⸱mes.) ("
 "met"____"sa⸱met⸱’ ā⸱ya⸱smā saṅ⸱ghe⸱na, "
 "mey"____"pa⸱mā⸱ṇaṁ vā a⸱tik⸱kā⸱mey⸱ya, "
 "meṇ"____"u⸱sa⸱bha⸱yud⸱dhaṁ a⸱ja⸱yud⸱dhaṁ meṇ⸱ḍa⸱yud⸱dhaṁ kuk⸱ku⸱ṭa⸱yud⸱dhaṁ vaṭ⸱ṭa⸱ka⸱yud⸱dhaṁ daṇ⸱ḍa⸱yud⸱dhaṁ muṭ⸱ṭhi⸱yud⸱dhaṁ nib⸱bud⸱dhaṁ uy⸱yo⸱dhi⸱kaṁ ba⸱lag⸱gaṁ se⸱nāb⸱yū⸱haṁ a⸱nī⸱ka⸱das⸱sa⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā vi⸱sū⸱ka⸱das⸱sa⸱nā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "mic"____"mic⸱chā pa⸱ṭi⸱pan⸱no tva⸱ma⸱si, "
 "mis"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "mit"____"tat⸱ra ce so bhik⸱khu pub⸱be ap⸱pa⸱vā⸱ri⸱to u⸱pa⸱saṅ⸱ka⸱mit⸱vā cī⸱va⸱re vi⸱kap⸱paṁ ā⸱paj⸱jey⸱ya, "
 "miñ"____"a⸱tha kho tā de⸱va⸱tā sey⸱ya⸱thā⸱pi nā⸱ma ba⸱la⸱vā pu⸱ri⸱so sam⸱miñ⸱ji⸱taṁ vā bā⸱haṁ pa⸱sā⸱rey⸱ya, "
 "miṁ"____"na te ga⸱mis⸱san⸱ti a⸱pā⸱ya-bhū⸱miṁ. "
 "mok"____"bhik⸱khu⸱pā⸱ṭi⸱mok⸱khaṁ   "
 "muc"____"a⸱yaṁ at⸱tā sam⸱mā sa⸱muc⸱chin⸱no ho⸱tī⸱’ti. "
 "mud"____"yo pa⸱na bhik⸱khu rañ⸱ño khat⸱ti⸱yas⸱sa mud⸱dhā⸱bhi⸱sit⸱tas⸱sa a⸱nik⸱khan⸱ta⸱rā⸱ja⸱ke a⸱nig⸱ga⸱ta⸱ra⸱ta⸱na⸱ke pub⸱be ap⸱pa⸱ṭi⸱saṁ⸱vi⸱di⸱to in⸱da⸱khī⸱laṁ a⸱tik⸱ka⸱mey⸱ya, "
 "muj"____"et⸱tha si⸱tā⸱va um⸱muj⸱ja⸱mā⸱nā um⸱muj⸱jan⸱ti, "
 "mup"____"a⸱dhic⸱ca⸱sa⸱mup⸱pan⸱na⸱vā⸱do (dn 1) ♦ 67. “"
 "mus"____"te⸱saṁ a⸱ti⸱ve⸱laṁ has⸱sa⸱khiḍ⸱ḍā⸱ra⸱ti⸱dham⸱ma⸱sa⸱mā⸱pan⸱nā⸱naṁ vi⸱ha⸱ra⸱taṁ sa⸱ti sam⸱mus⸱sa⸱ti {"
 "mut"____"na ca tas⸱sa bhik⸱khu⸱no añ⸱ñāṇ⸱na⸱ke⸱na mut⸱ti at⸱thi: "
 "muñ"____"mā vo muñ⸱cit⸱tha ko⸱ci naṁ."
 "muḷ"____"co⸱ro⸱’si bā⸱lo⸱’si muḷ⸱ho⸱’si the⸱no⸱’sī”"
 "muṁ"____"mo⸱da⸱mā⸱nā a⸱bhik⸱kā⸱muṁ "
 "muṭ"____"u⸱sa⸱bha⸱yud⸱dhaṁ a⸱ja⸱yud⸱dhaṁ meṇ⸱ḍa⸱yud⸱dhaṁ kuk⸱ku⸱ṭa⸱yud⸱dhaṁ vaṭ⸱ṭa⸱ka⸱yud⸱dhaṁ daṇ⸱ḍa⸱yud⸱dhaṁ muṭ⸱ṭhi⸱yud⸱dhaṁ nib⸱bud⸱dhaṁ uy⸱yo⸱dhi⸱kaṁ ba⸱lag⸱gaṁ se⸱nāb⸱yū⸱haṁ a⸱nī⸱ka⸱das⸱sa⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā vi⸱sū⸱ka⸱das⸱sa⸱nā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "mūḷ"____"a⸱mūḷ⸱ha⸱vi⸱na⸱yo dā⸱tab⸱bo   4. "
 "nab"____"so ca bhik⸱khu a⸱nab⸱bhi⸱to, "
 "nac"____"nac⸱ca⸱gī⸱ta⸱vā⸱di⸱ta⸱vi⸱sū⸱ka⸱das⸱sa⸱nā {"
 "nad"____"yo pa⸱na bhik⸱khu mañ⸱caṁ vā pī⸱ṭhaṁ vā tū⸱lo⸱nad⸱dhaṁ kā⸱rā⸱pey⸱ya, "
 "nak"____"nak⸱khat⸱tā⸱ni pu⸱rak⸱khit⸱vā "
 "nam"____"mā ā⸱ya⸱sman⸱tā⸱nam⸱’pi saṅ⸱gha⸱bhe⸱do ru⸱cit⸱tha, "
 "nan"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "nap"____"yo pa⸱na bhik⸱khu nā⸱nap⸱pa⸱kā⸱ra⸱kaṁ rū⸱pi⸱ya⸱saṁ⸱vo⸱hā⸱raṁ sa⸱mā⸱paj⸱jey⸱ya, "
 "nas"____"ū⸱nas⸱sa pā⸱ri⸱pū⸱ri⸱yā, "
 "nat"____"tat⸱tha pu⸱ri⸱me⸱su ca⸱tū⸱su kic⸱ce⸱su pa⸱dī⸱pa⸱kic⸱caṁ i⸱dā⸱ni su⸱ri⸱ya⸱lo⸱kas⸱sa at⸱thi⸱tā⸱ya nat⸱thi. "
 "nath"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "nay"____"san⸱nay⸱hit⸱vā ba⸱liṁ se⸱naṁ "
 "nañ"____"taṇ⸱ṭhā⸱na⸱sam⸱maj⸱ja⸱nañ⸱ca;         "
 "naḍ"____"o⸱re⸱n’aḍ⸱ḍha⸱mā⸱so se⸱so gim⸱hā⸱nan⸱’ti kat⸱vā ni⸱vā⸱sey⸱ya, "
 "naṁ"____"chan⸱dā⸱ra⸱hā⸱naṁ bhik⸱khū⸱naṁ chan⸱dā⸱ha⸱ra⸱ṇañ⸱ca;         "
 "naṅ"____"sa⸱naṅ⸱ku⸱mā⸱ro tis⸱so ca "
 "naṭ"____"ac⸱chin⸱na⸱cī⸱va⸱ro vā ho⸱ti bhik⸱khu naṭ⸱ṭha⸱cī⸱va⸱ro vā, "
 "net"____"sā⸱ra⸱thī va net⸱tā⸱ni ga⸱het⸱vā "
 "ney"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "nhā"____"yo pa⸱na bhik⸱khu o⸱re⸱naḍ⸱ḍha⸱mā⸱saṁ nhā⸱yey⸱ya, "
 "nib"____"tat⸱ra tum⸱he⸱hi a⸱bhū⸱taṁ a⸱bhū⸱ta⸱to nib⸱be⸱ṭhe⸱tab⸱baṁ — ‘"
 "nic"____"añ⸱ñat⸱ra nic⸱ca⸱pa⸱vā⸱ra⸱ṇā⸱ya, "
 "nid"____"cī⸱va⸱rat⸱thi⸱ke⸱na bhik⸱kha⸱ve bhik⸱khu⸱nā vey⸱yā⸱vac⸱ca⸱ka⸱ro nid⸱di⸱si⸱tab⸱bo ā⸱rā⸱mi⸱ko vā u⸱pā⸱sa⸱ko vā, “"
 "nig"____"yo pa⸱na bhik⸱khu rañ⸱ño khat⸱ti⸱yas⸱sa mud⸱dhā⸱bhi⸱sit⸱tas⸱sa a⸱nik⸱khan⸱ta⸱rā⸱ja⸱ke a⸱nig⸱ga⸱ta⸱ra⸱ta⸱na⸱ke pub⸱be ap⸱pa⸱ṭi⸱saṁ⸱vi⸱di⸱to in⸱da⸱khī⸱laṁ a⸱tik⸱ka⸱mey⸱ya, "
 "nij"____"te a⸱ti⸱ve⸱laṁ añ⸱ña⸱mañ⸱ñaṁ u⸱pa⸱nij⸱jhā⸱yan⸱ti. "
 "nik"____"i⸱ti sa⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ ka⸱tat⸱tā nik⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ pa⸱ka⸱ti⸱yā pa⸱ri⸱niṭ⸱ṭhi⸱tat⸱tā e⸱van⸱taṁ na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ pa⸱ri⸱niṭ⸱ṭhi⸱taṁ ho⸱ti.   "
 "nil"____"na hat⸱tha⸱nil⸱le⸱ha⸱kaṁ bhuñ⸱jis⸱sā⸱mī⸱’ti, "
 "nim"____"nim⸱mā⸱na⸱ra⸱ti⸱no ā⸱gū "
 "nin"____"añ⸱ño at⸱tā dib⸱bo rū⸱pī ma⸱no⸱ma⸱yo sab⸱baṅ⸱ga⸱pac⸱caṅ⸱gī a⸱hī⸱nin⸱dri⸱yo. "
 "nip"____"dvit⸱tik⸱kha⸱tuṁ co⸱da⸱ya⸱mā⸱no sā⸱ra⸱ya⸱mā⸱no taṁ cī⸱va⸱raṁ a⸱bhi⸱nip⸱phā⸱dey⸱ya, "
 "nis"____"so bhik⸱khu bhik⸱khū⸱hi yā⸱va⸱ta⸱ti⸱yaṁ sa⸱ma⸱nu⸱bhā⸱si⸱tab⸱bo tas⸱sa pa⸱ṭi⸱nis⸱sag⸱gā⸱ya, "
 "niy"____"rañ⸱ñaṁ niy⸱yā⸱naṁ bha⸱vis⸱sa⸱ti, "
 "niṁ"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ta⸱kaṁ ga⸱ha⸱pa⸱tiṁ vā ga⸱ha⸱pa⸱tā⸱niṁ vā cī⸱va⸱raṁ viñ⸱ñā⸱pey⸱ya añ⸱ñat⸱ra sa⸱ma⸱yā, "
 "niṭ"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "nud"____"ni⸱dā⸱nud⸱de⸱so niṭ⸱ṭhi⸱to.)   "
 "nug"____"ta⸱to a⸱pa⸱re⸱na sa⸱ma⸱ye⸱na sa⸱ma⸱nug⸱gā⸱hi⸱ya⸱mā⸱no vā a⸱sa⸱ma⸱nug⸱gā⸱hi⸱ya⸱mā⸱no vā ā⸱pan⸱no vi⸱sud⸱dhā⸱pek⸱kho e⸱vaṁ va⸱dey⸱ya, “"
 "nuk"____"yā⸱va⸱ti⸱kā ca bhik⸱khu kam⸱map⸱pat⸱tā  saṅ⸱ghu⸱po⸱sa⸱thā⸱ra⸱hā cat⸱tā⸱ro vā ta⸱to vā a⸱ti⸱re⸱kā pa⸱ka⸱tat⸱tā pā⸱rā⸱ji⸱kaṁ a⸱nā⸱pan⸱nā saṅ⸱ghe⸱na vā a⸱nuk⸱khit⸱tā, "
 "nup"____"up⸱pan⸱nup⸱pan⸱nā⸱naṁ a⸱dhi⸱ka⸱ra⸱ṇā⸱naṁ sa⸱ma⸱thā⸱ya vū⸱pa⸱sa⸱mā⸱ya :    1. "
 "nus"____"e⸱vaṁ e⸱vaṁ e⸱va⸱rū⸱pā⸱ya pa⸱ri⸱sā⸱ya yā⸱va⸱ta⸱ti⸱yaṁ a⸱nus⸱sā⸱vi⸱taṁ ho⸱ti. "
 "nut"____"kā⸱ya⸱nut⸱tha, "
 "nāb"____"dvi⸱rat⸱ta⸱ti⸱rat⸱tañ⸱ce bhik⸱khu se⸱nā⸱ya va⸱sa⸱mā⸱no uy⸱yo⸱dhi⸱kaṁ vā ba⸱lag⸱gaṁ vā se⸱nāb⸱yū⸱haṁ vā a⸱nī⸱ka⸱das⸱sa⸱naṁ vā gac⸱chey⸱ya, "
 "ok"____"ok⸱khit⸱ta⸱cak⸱khu an⸱ta⸱ra⸱gha⸱re ga⸱mis⸱sā⸱mī⸱’ti,  "
 "ot"____"ot⸱tha⸱rey⸱ya. "
 "oṭ"____"na oṭ⸱ṭha⸱nil⸱le⸱ha⸱kaṁ bhuñ⸱jis⸱sā⸱mī⸱’ti, "
 "pab"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "pac"____"ya⸱thā kho pa⸱na pac⸱ce⸱ka⸱puṭ⸱ṭhas⸱sa  "
 "pag"____"yo pa⸱na bhik⸱khu sa⸱mag⸱gas⸱sa saṅ⸱ghas⸱sa bhe⸱dā⸱ya pa⸱rak⸱ka⸱mey⸱ya bhe⸱da⸱na⸱saṁ⸱vat⸱ta⸱ni⸱kaṁ vā a⸱dhi⸱ka⸱ra⸱ṇaṁ sa⸱mā⸱dā⸱ya pag⸱gay⸱ha tiṭ⸱ṭhey⸱ya, "
 "paj"____"ye⸱saṁ bhik⸱khu añ⸱ña⸱ta⸱raṁ vā añ⸱ña⸱ta⸱raṁ vā ā⸱paj⸱jit⸱vā na la⸱bha⸱ti bhik⸱khū⸱hi sad⸱dhiṁ saṁ⸱vā⸱saṁ, "
 "pak"____"i⸱mi⸱nā pak⸱khe⸱na.          "
 "pal"____"na pal⸱lat⸱thi⸱kā⸱ya an⸱ta⸱ra⸱gha⸱re ni⸱sī⸱dis⸱sā⸱mī⸱’ti, "
 "pan"____"yā⸱va⸱ti⸱kā ca bhik⸱khu kam⸱map⸱pat⸱tā  saṅ⸱ghu⸱po⸱sa⸱thā⸱ra⸱hā cat⸱tā⸱ro vā ta⸱to vā a⸱ti⸱re⸱kā pa⸱ka⸱tat⸱tā pā⸱rā⸱ji⸱kaṁ a⸱nā⸱pan⸱nā saṅ⸱ghe⸱na vā a⸱nuk⸱khit⸱tā, "
 "pas"____"i⸱ti pas⸱sā⸱mī” "
 "pat"____"e⸱ko u⸱po⸱sa⸱tho sam⸱pat⸱to,          "
 "pav"____"saṇ⸱hā⸱hi vā⸱cā⸱hi u⸱pav⸱ha⸱yan⸱tā "
 "pañ"____"ā⸱sa⸱na⸱pañ⸱ña⸱pa⸱nañ⸱ca;          "
 "paṁ"____"kā⸱tuṁ yut⸱ta⸱rū⸱paṁ.   "
 "paṅ"____"aṭ⸱ṭha⸱pa⸱daṁ da⸱sa⸱pa⸱daṁ ā⸱kā⸱saṁ pa⸱ri⸱hā⸱ra⸱pa⸱thaṁ san⸱ti⸱kaṁ kha⸱li⸱kaṁ gha⸱ṭi⸱kaṁ sa⸱lā⸱ka⸱hat⸱thaṁ ak⸱khaṁ paṅ⸱ga⸱cī⸱raṁ vaṅ⸱ka⸱kaṁ mok⸱kha⸱ci⸱kaṁ ciṅ⸱gu⸱li⸱kaṁ {"
 "paṇ"____"sa⸱ce so di⸱va⸱so cā⸱tud⸱da⸱si-paṇ⸱ṇa⸱ra⸱sī sā⸱mag⸱gī⸱na⸱mañ⸱ña⸱ta⸱ro ya⸱thāj⸱ja u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so,   "
 "paṭ"____"pā⸱nī⸱ya⸱pa⸱ri⸱bho⸱ja⸱nī⸱yū⸱paṭ⸱ṭha⸱pa⸱nañ⸱ca;          "
 "pek"____"ta⸱smā sa⸱ra⸱mā⸱ne⸱na bhik⸱khu⸱nā ā⸱pan⸱ne⸱na vi⸱sud⸱dhā⸱pek⸱khe⸱na san⸱tī ā⸱pat⸱ti ā⸱vi⸱kā⸱tab⸱bā, "
 "pen"____"ya⸱thā vā pa⸱ne⸱ke bhon⸱to sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā sad⸱dhā⸱dey⸱yā⸱ni bho⸱ja⸱nā⸱ni bhuñ⸱jit⸱vā te e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱ve⸱na jī⸱vi⸱taṁ kap⸱pen⸱ti, "
 "pet"____"i⸱mi⸱nā cī⸱va⸱ra⸱ce⸱tā⸱pa⸱ne⸱na cī⸱va⸱raṁ ce⸱tā⸱pet⸱vā it⸱than⸱nā⸱maṁ bhik⸱khuṁ cī⸱va⸱re⸱na ac⸱chā⸱des⸱sā⸱mī”"
 "pey"____"yo pa⸱na bhik⸱khu sañ⸱cic⸱ca ma⸱nus⸱sa⸱vig⸱ga⸱haṁ jī⸱vi⸱tā vo⸱ro⸱pey⸱ya,  "
 "phan"____"pa⸱ri⸱tas⸱si⸱ta⸱vip⸱phan⸱di⸱ta⸱vā⸱ro (dn 1) ♦ 105. “"
 "phap"____"sam⸱phap⸱pa⸱lā⸱paṁ pa⸱hā⸱ya sam⸱phap⸱pa⸱lā⸱pā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo kā⸱la⸱vā⸱dī bhū⸱ta⸱vā⸱dī at⸱tha⸱vā⸱dī dham⸱ma⸱vā⸱dī vi⸱na⸱ya⸱vā⸱dī, "
 "phas"____"phas⸱sa⸱pac⸱ca⸱yā⸱vā⸱ro (dn 1) ♦ 118. “"
 "phus"____"sab⸱be te cha⸱hi phas⸱sā⸱ya⸱ta⸱ne⸱hi phus⸱sa phus⸱sa pa⸱ṭi⸱saṁ⸱ve⸱den⸱ti te⸱saṁ ve⸱da⸱nā⸱pac⸱ca⸱yā taṇ⸱hā, "
 "pin"____"tuc⸱chaṁ mu⸱sā vi⸱la⸱pin”"
 "pis"____"pa⸱ri⸱maṇ⸱ḍa⸱laṁ pā⸱ru⸱pis⸱sā⸱mī⸱’ti, "
 "pit"____"sa⸱has⸱sī (kat⸱tha⸱ci)} lo⸱ka⸱dhā⸱tu a⸱kam⸱pit⸱thā⸱ti."
 "piṁ"____"yā sā vā⸱cā ne⸱lā kaṇ⸱ṇa⸱su⸱khā pe⸱ma⸱nī⸱yā ha⸱da⸱yaṅ⸱ga⸱mā po⸱rī ba⸱hu⸱ja⸱na⸱kan⸱tā ba⸱hu⸱ja⸱na⸱ma⸱nā⸱pā ta⸱thā⸱rū⸱piṁ vā⸱caṁ bhā⸱si⸱tā⸱’ti — "
 "piṇ"____"e⸱vañ⸱ca so bhik⸱khu vat⸱vā kiñ⸱ci⸱mat⸱taṁ a⸱nu⸱pa⸱daj⸱jey⸱ya an⸱ta⸱ma⸱so piṇ⸱ḍa⸱pā⸱ta⸱mat⸱tam⸱’pi, "
 "piṭ"____"i⸱ti⸱ha te u⸱bho ā⸱ca⸱ri⸱yan⸱te⸱vā⸱sī añ⸱ña⸱mañ⸱ñas⸱sa u⸱ju⸱vi⸱pac⸱ca⸱nī⸱ka⸱vā⸱dā bha⸱ga⸱van⸱taṁ piṭ⸱ṭhi⸱to piṭ⸱ṭhi⸱to a⸱nu⸱ban⸱dhā {"
 "pub"____"pub⸱ba⸱kic⸱caṁ   "
 "puc"____"tatth’ ā⸱ya⸱sman⸱te puc⸱chā⸱mi : "
 "pug"____"te⸱sañ⸱ca  hat⸱tha⸱pā⸱se  hat⸱tha⸱pā⸱sa⸱to ba⸱hi⸱ka⸱ra⸱ṇa⸱va⸱se⸱na vaj⸱je⸱tab⸱bo ko⸱ci vaj⸱ja⸱nī⸱ya⸱pug⸱ga⸱lo ce nat⸱thi.   "
 "puj"____"tat⸱tha pa⸱dī⸱puj⸱ja⸱la⸱nañ⸱ca;          "
 "pul"____"ve⸱pul⸱las⸱sa ni⸱ve⸱sa⸱naṁ "
 "pup"____"um⸱mā-pup⸱pha⸱ni⸱bhā⸱si⸱no "
 "put"____"put⸱tā⸱pi tas⸱sa ba⸱ha⸱vo "
 "puñ"____"a⸱tha kho añ⸱ña⸱ta⸱ro sat⸱to ā⸱yuk⸱kha⸱yā vā puñ⸱ñak⸱kha⸱yā vā ā⸱bhas⸱sa⸱ra⸱kā⸱yā ca⸱vit⸱vā suñ⸱ñaṁ brah⸱ma⸱vi⸱mā⸱naṁ u⸱pa⸱paj⸱ja⸱ti. "
 "puṇ"____"da⸱sā⸱hā⸱nā⸱ga⸱taṁ kat⸱ti⸱ka⸱te⸱mā⸱si⸱puṇ⸱ṇa⸱maṁ, "
 "puṭ"____"ya⸱thā kho pa⸱na pac⸱ce⸱ka⸱puṭ⸱ṭhas⸱sa  "
 "rab"____"sa⸱mā⸱rab⸱bhā (sī. "
 "rac"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ sik⸱khā⸱sā⸱jī⸱va⸱sa⸱mā⸱pan⸱no sik⸱khaṁ ap⸱pac⸱cak⸱khā⸱ya dub⸱bal⸱yaṁ a⸱nā⸱vi⸱kat⸱vā me⸱thu⸱naṁ dham⸱maṁ pa⸱ṭi⸱se⸱vey⸱ya an⸱ta⸱ma⸱so ti⸱rac⸱chā⸱na⸱ga⸱tā⸱ya⸱’pi; "
 "rad"____"tat⸱ra tum⸱he⸱hi na ā⸱ghā⸱to na ap⸱pac⸱ca⸱yo na ce⸱ta⸱so a⸱na⸱bhi⸱rad⸱dhi ka⸱ra⸱ṇī⸱yā. "
 "rah"____"sub⸱rah⸱mā pa⸱ra⸱mat⸱to ca "
 "rak"____"yo pa⸱na bhik⸱khu sa⸱mag⸱gas⸱sa saṅ⸱ghas⸱sa bhe⸱dā⸱ya pa⸱rak⸱ka⸱mey⸱ya bhe⸱da⸱na⸱saṁ⸱vat⸱ta⸱ni⸱kaṁ vā a⸱dhi⸱ka⸱ra⸱ṇaṁ sa⸱mā⸱dā⸱ya pag⸱gay⸱ha tiṭ⸱ṭhey⸱ya, "
 "ram"____"te⸱hi bhik⸱khū⸱hi vat⸱thuṁ de⸱se⸱tab⸱baṁ a⸱nā⸱ram⸱bhaṁ sa⸱pa⸱rik⸱ka⸱ma⸱naṁ. "
 "ran"____"u⸱pa⸱vas⸱saṁ kho pa⸱na kat⸱ti⸱ka⸱puṇ⸱ṇa⸱maṁ yā⸱ni kho pa⸱na tā⸱ni ā⸱rañ⸱ñna⸱kā⸱ni se⸱nā⸱sa⸱nā⸱ni sā⸱saṅ⸱ka⸱sam⸱ma⸱tā⸱ni sap⸱pa⸱ṭi⸱bha⸱yā⸱ni ta⸱thā⸱rū⸱pe⸱su bhik⸱khu se⸱nā⸱sa⸱ne⸱su vi⸱ha⸱ran⸱to ā⸱kaṅ⸱kha⸱mā⸱no tiṇ⸱ṇaṁ cī⸱va⸱rā⸱naṁ añ⸱ña⸱ta⸱raṁ cī⸱va⸱raṁ an⸱ta⸱ra⸱gha⸱re nik⸱khi⸱pey⸱ya, "
 "rap"____"yo pa⸱na bhik⸱khu su⸱ga⸱ta⸱cī⸱va⸱rap⸱pa⸱mā⸱ṇaṁ cī⸱va⸱raṁ kā⸱rā⸱pey⸱ya a⸱ti⸱re⸱kaṁ vā, "
 "ras"____"hat⸱tha⸱gā⸱haṁ vā ve⸱ṇi⸱gā⸱haṁ vā añ⸱ña⸱ta⸱ras⸱sa vā añ⸱ña⸱ta⸱ras⸱sa vā aṅ⸱gas⸱sa pa⸱rā⸱ma⸱sa⸱naṁ, "
 "rat"____"yo pa⸱na bhik⸱khu sañ⸱ca⸱rit⸱taṁ sa⸱mā⸱paj⸱jey⸱ya it⸱thi⸱yā vā pu⸱ri⸱sa⸱ma⸱tiṁ pu⸱ri⸱sas⸱sa vā it⸱thī⸱ma⸱tiṁ jā⸱yat⸱ta⸱ne vā jā⸱rat⸱ta⸱ne vā an⸱ta⸱ma⸱so taṁ kha⸱ṇi⸱kā⸱ya⸱’ pi, "
 "ray"____"te ca bhik⸱khū gā⸱ray⸱hā, "
 "rañ"____"yo pa⸱na bhik⸱khu gā⸱mā vā a⸱rañ⸱ñā vā a⸱din⸱naṁ they⸱ya⸱saṅ⸱khā⸱taṁ ā⸱di⸱yey⸱ya, "
 "raṁ"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "raṭ"____"dha⸱ta⸱raṭ⸱ṭho pa⸱sā⸱sa⸱ti "
 "res"____"de⸱va-kā⸱yaṁ pa⸱ri⸱pū⸱res⸱san⸱tī⸱ti.”  "
 "rey"____"saṅ⸱gho u⸱po⸱sa⸱thaṁ ka⸱rey⸱ya pā⸱ṭi⸱mok⸱khaṁ ud⸱di⸱sey⸱ya.   "
 "rib"____"yo pa⸱na bhik⸱khu a⸱ce⸱la⸱kas⸱sa vā pa⸱rib⸱bā⸱ja⸱kas⸱sa vā pa⸱rib⸱bā⸱ji⸱kā⸱ya vā sa⸱hat⸱thā khā⸱da⸱nī⸱yaṁ vā bho⸱ja⸱nī⸱yaṁ vā da⸱dey⸱ya, "
 "rid"____"yo pa⸱na bhik⸱khu a⸱nu⸱pa⸱sam⸱pan⸱ne⸱na ut⸱ta⸱rid⸱vi⸱rat⸱ta⸱ti⸱rat⸱taṁ sa⸱ha⸱sey⸱yaṁ kap⸱pey⸱ya, "
 "rik"____"te⸱hi bhik⸱khū⸱hi vat⸱thuṁ de⸱se⸱tab⸱baṁ a⸱nā⸱ram⸱bhaṁ sa⸱pa⸱rik⸱ka⸱ma⸱naṁ. "
 "rim"____"te ma⸱yaṁ a⸱ti⸱ve⸱laṁ has⸱sa⸱khiḍ⸱ḍā⸱ra⸱ti⸱dham⸱ma⸱sa⸱mā⸱pan⸱nā vi⸱ha⸱rim⸱hā. "
 "rin"____"sak⸱ko⸱p’ā⸱ga pu⸱rin⸱da⸱do "
 "ris"____"ra⸱ta⸱naṁ vā pa⸱na bhik⸱khu⸱nā ra⸱ta⸱na⸱sam⸱ma⸱taṁ vā aj⸱jhā⸱rā⸱me vā aj⸱jhā⸱va⸱sa⸱the vā ug⸱ga⸱het⸱vā vā ug⸱gaṇ⸱hā⸱pet⸱vā vā nik⸱khi⸱pi⸱tab⸱baṁ “yas⸱sa bha⸱vis⸱sa⸱ti so ha⸱ris⸱sa⸱tī” "
 "rit"____"yo pa⸱na bhik⸱khu sañ⸱ca⸱rit⸱taṁ sa⸱mā⸱paj⸱jey⸱ya it⸱thi⸱yā vā pu⸱ri⸱sa⸱ma⸱tiṁ pu⸱ri⸱sas⸱sa vā it⸱thī⸱ma⸱tiṁ jā⸱yat⸱ta⸱ne vā jā⸱rat⸱ta⸱ne vā an⸱ta⸱ma⸱so taṁ kha⸱ṇi⸱kā⸱ya⸱’ pi, "
 "riv"____"ā⸱vā⸱ha⸱naṁ vi⸱vā⸱ha⸱naṁ saṁ⸱va⸱ra⸱ṇaṁ vi⸱va⸱ra⸱ṇaṁ saṁ⸱ki⸱ra⸱ṇaṁ vi⸱ki⸱ra⸱ṇaṁ su⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ dub⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ vi⸱rud⸱dha⸱gab⸱bha⸱ka⸱ra⸱ṇaṁ jiv⸱hā⸱ni⸱ban⸱dha⸱naṁ ha⸱nu⸱saṁ⸱ha⸱na⸱naṁ hat⸱thā⸱bhi⸱jap⸱pa⸱naṁ ha⸱nu⸱jap⸱pa⸱naṁ kaṇ⸱ṇa⸱jap⸱pa⸱naṁ ā⸱dā⸱sa⸱pañ⸱haṁ ku⸱mā⸱ri⸱ka⸱pañ⸱haṁ de⸱va⸱pañ⸱haṁ ā⸱dic⸱cu⸱paṭ⸱ṭhā⸱naṁ ma⸱ha⸱tu⸱paṭ⸱ṭhā⸱naṁ ab⸱bhuj⸱ja⸱la⸱naṁ si⸱riv⸱hā⸱ya⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "riñ"____"tañ⸱ca ya⸱thā⸱dham⸱mo kā⸱re⸱tab⸱bo ut⸱ta⸱riñ⸱c’as⸱sa mo⸱ho  ā⸱ro⸱pe⸱tab⸱bo, “"
 "riṁ"____"e⸱ta⸱dag⸱gaṁ bha⸱gi⸱ni pā⸱ri⸱ca⸱ri⸱yā⸱naṁ yā mā⸱di⸱saṁ sī⸱la⸱van⸱taṁ kal⸱yā⸱ṇa⸱dham⸱maṁ brah⸱ma⸱cā⸱riṁ e⸱te⸱na dham⸱me⸱na pā⸱ri⸱ca⸱rey⸱yā”"
 "riṭ"____"a⸱riṭ⸱ṭha⸱kā ca ro⸱jā ca "
 "rog"____"ā⸱rog⸱yaṁ bha⸱vis⸱sa⸱ti, "
 "rud"____"ā⸱vā⸱ha⸱naṁ vi⸱vā⸱ha⸱naṁ saṁ⸱va⸱ra⸱ṇaṁ vi⸱va⸱ra⸱ṇaṁ saṁ⸱ki⸱ra⸱ṇaṁ vi⸱ki⸱ra⸱ṇaṁ su⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ dub⸱bha⸱ga⸱ka⸱ra⸱ṇaṁ vi⸱rud⸱dha⸱gab⸱bha⸱ka⸱ra⸱ṇaṁ jiv⸱hā⸱ni⸱ban⸱dha⸱naṁ ha⸱nu⸱saṁ⸱ha⸱na⸱naṁ hat⸱thā⸱bhi⸱jap⸱pa⸱naṁ ha⸱nu⸱jap⸱pa⸱naṁ kaṇ⸱ṇa⸱jap⸱pa⸱naṁ ā⸱dā⸱sa⸱pañ⸱haṁ ku⸱mā⸱ri⸱ka⸱pañ⸱haṁ de⸱va⸱pañ⸱haṁ ā⸱dic⸱cu⸱paṭ⸱ṭhā⸱naṁ ma⸱ha⸱tu⸱paṭ⸱ṭhā⸱naṁ ab⸱bhuj⸱ja⸱la⸱naṁ si⸱riv⸱hā⸱ya⸱naṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "rum"____"suk⸱kā ka⸱rum⸱hā a⸱ru⸱ṇā "
 "rup"____"chab⸱bī⸱sa⸱ti sā⸱rup⸱pā.   1. "
 "rut"____"san⸱ta⸱rut⸱ta⸱ra⸱pa⸱ra⸱man⸱’te⸱na bhik⸱khu⸱nā ta⸱to cī⸱va⸱raṁ sā⸱di⸱tab⸱baṁ, "
 "ruṁ"____"te ca ā⸱tap⸱pa⸱m-a⸱ka⸱ruṁ "
 "rāh"____"ya⸱thā vā pa⸱ne⸱ke bhon⸱to sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā sad⸱dhā⸱dey⸱yā⸱ni bho⸱ja⸱nā⸱ni bhuñ⸱jit⸱vā te e⸱va⸱rū⸱paṁ bī⸱ja⸱gā⸱ma⸱bhū⸱ta⸱gā⸱ma⸱sa⸱mā⸱ram⸱bhaṁ a⸱nu⸱yut⸱tā vi⸱ha⸱ran⸱ti, "
 "rūḷ"____"na pā⸱du⸱kā⸱rūḷ⸱has⸱sa a⸱gi⸱lā⸱nas⸱sa dham⸱maṁ de⸱sis⸱sā⸱mī⸱’ti, "
 "sab"____"i⸱ti e⸱vaṁ sab⸱be⸱hi ā⸱ya⸱sman⸱te⸱hi u⸱tuk⸱khā⸱naṁ  dhā⸱re⸱tab⸱baṁ.                              ("
 "sac"____"mu⸱sā⸱vā⸱daṁ pa⸱hā⸱ya mu⸱sā⸱vā⸱dā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo sac⸱ca⸱vā⸱dī sac⸱ca⸱san⸱dho the⸱to {"
 "sad"____"ye⸱saṁ bhik⸱khu añ⸱ña⸱ta⸱raṁ vā añ⸱ña⸱ta⸱raṁ vā ā⸱paj⸱jit⸱vā na la⸱bha⸱ti bhik⸱khū⸱hi sad⸱dhiṁ saṁ⸱vā⸱saṁ, "
 "sag"____"yo pa⸱na bhik⸱khu o⸱tiṇ⸱ṇo vi⸱pa⸱ri⸱ṇa⸱te⸱na cit⸱te⸱na mā⸱tu⸱gā⸱me⸱na sad⸱dhiṁ kā⸱ya⸱saṁ⸱sag⸱gaṁ sa⸱mā⸱paj⸱jey⸱ya, "
 "saj"____"yā⸱va⸱ta⸱ti⸱yañ⸱’ce sa⸱ma⸱nu⸱bhā⸱si⸱ya⸱mā⸱no taṁ pa⸱ṭi⸱nis⸱saj⸱jey⸱ya ic⸱c’e⸱taṁ ku⸱sa⸱laṁ. "
 "sak"____"a⸱pa⸱sak⸱ka tā⸱va bha⸱gi⸱ni, "
 "sal"____"pu⸱thū sī⸱hā⸱va sal⸱lī⸱nā "
 "sam"____"taṇ⸱ṭhā⸱na⸱sam⸱maj⸱ja⸱nañ⸱ca;         "
 "san"____"u⸱po⸱sa⸱that⸱thā⸱ya san⸱ni⸱pa⸱ti⸱tā bhik⸱khū et⸱ta⸱kā⸱ti bhik⸱khū⸱naṁ ga⸱ṇa⸱nā,   "
 "sap"____"sap⸱pi, "
 "sas"____"yo pa⸱na bhik⸱khu sañ⸱ca⸱rit⸱taṁ sa⸱mā⸱paj⸱jey⸱ya it⸱thi⸱yā vā pu⸱ri⸱sa⸱ma⸱tiṁ pu⸱ri⸱sas⸱sa vā it⸱thī⸱ma⸱tiṁ jā⸱yat⸱ta⸱ne vā jā⸱rat⸱ta⸱ne vā an⸱ta⸱ma⸱so taṁ kha⸱ṇi⸱kā⸱ya⸱’ pi, "
 "sat"____"sat⸱tha⸱hā⸱ra⸱kaṁ vās⸱sa pa⸱ri⸱ye⸱sey⸱ya, "
 "satt"____"dī⸱gha⸱so dvā⸱da⸱sa vi⸱dat⸱thi⸱yo su⸱ga⸱ta⸱vi⸱dat⸱thi⸱yā ti⸱ri⸱yaṁ satt’ an⸱ta⸱rā. "
 "sañ"____"te⸱sañ⸱ñe⸱va a⸱ka⸱tu⸱po⸱sa⸱thā⸱naṁ pā⸱ri⸱sud⸱dhi⸱yā⸱pi ā⸱ha⸱ra⸱ṇañ⸱ca;          "
 "saṁ"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "saṅ"____"yā⸱va⸱ti⸱kā ca bhik⸱khu kam⸱map⸱pat⸱tā  saṅ⸱ghu⸱po⸱sa⸱thā⸱ra⸱hā cat⸱tā⸱ro vā ta⸱to vā a⸱ti⸱re⸱kā pa⸱ka⸱tat⸱tā pā⸱rā⸱ji⸱kaṁ a⸱nā⸱pan⸱nā saṅ⸱ghe⸱na vā a⸱nuk⸱khit⸱tā, "
 "saṇ"____"saṇ⸱hā⸱hi vā⸱cā⸱hi u⸱pav⸱ha⸱yan⸱tā "
 "saṭ"____"sañ⸱ce⸱ta⸱ni⸱kā suk⸱ka⸱vi⸱saṭ⸱ṭhi añ⸱ñat⸱ra su⸱pi⸱nan⸱tā saṅ⸱ghā⸱di⸱se⸱so.   2. "
 "sek"____"yā⸱ni kho pa⸱na tā⸱ni sek⸱kha⸱sam⸱ma⸱tā⸱ni ku⸱lā⸱ni. "
 "sen"____"te a⸱ti⸱ve⸱laṁ añ⸱ña⸱mañ⸱ñaṁ u⸱pa⸱nij⸱jhā⸱yan⸱tā añ⸱ña⸱mañ⸱ñam⸱hi cit⸱tā⸱ni pa⸱dū⸱sen⸱ti. "
 "ses"____"pa⸱ri⸱maṇ⸱ḍa⸱laṁ ni⸱vā⸱ses⸱sā⸱mī⸱’ti, "
 "set"____"da⸱s’et⸱tha is⸱sa⸱rā ā⸱gū "
 "sey"____"saṅ⸱gho u⸱po⸱sa⸱thaṁ ka⸱rey⸱ya pā⸱ṭi⸱mok⸱khaṁ ud⸱di⸱sey⸱ya.   "
 "seṭ"____"can⸱da⸱no kā⸱ma-seṭ⸱ṭho ca "
 "sib"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ti⸱kā⸱ya bhik⸱khu⸱ni⸱yā cī⸱va⸱raṁ sib⸱bey⸱ya vā sib⸱bā⸱pey⸱ya vā, "
 "sik"____"yo pa⸱na bhik⸱khu bhik⸱khū⸱naṁ sik⸱khā⸱sā⸱jī⸱va⸱sa⸱mā⸱pan⸱no sik⸱khaṁ ap⸱pac⸱cak⸱khā⸱ya dub⸱bal⸱yaṁ a⸱nā⸱vi⸱kat⸱vā me⸱thu⸱naṁ dham⸱maṁ pa⸱ṭi⸱se⸱vey⸱ya an⸱ta⸱ma⸱so ti⸱rac⸱chā⸱na⸱ga⸱tā⸱ya⸱’pi; "
 "sim"____"te ma⸱yaṁ a⸱ti⸱ve⸱laṁ añ⸱ña⸱mañ⸱ñaṁ u⸱pa⸱nij⸱jhā⸱yan⸱tā añ⸱ña⸱mañ⸱ñam⸱hi cit⸱tā⸱ni pa⸱dū⸱sim⸱hā, "
 "sin"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "sis"____"pā⸱ṭi⸱mok⸱khaṁ ud⸱di⸱sis⸱sā⸱mi, "
 "sit"____"yo pa⸱na bhik⸱khu rañ⸱ño khat⸱ti⸱yas⸱sa mud⸱dhā⸱bhi⸱sit⸱tas⸱sa a⸱nik⸱khan⸱ta⸱rā⸱ja⸱ke a⸱nig⸱ga⸱ta⸱ra⸱ta⸱na⸱ke pub⸱be ap⸱pa⸱ṭi⸱saṁ⸱vi⸱di⸱to in⸱da⸱khī⸱laṁ a⸱tik⸱ka⸱mey⸱ya, "
 "siñ"____"yo pa⸱na bhik⸱khu jā⸱naṁ sap⸱pā⸱ṇa⸱kaṁ u⸱da⸱kaṁ ti⸱ṇaṁ vā mat⸱ti⸱kaṁ vā siñ⸱cey⸱ya vā siñ⸱cā⸱pey⸱ya vā, "
 "siṁ"____"yo pa⸱na bhik⸱khu saṅ⸱ghi⸱kaṁ mañ⸱caṁ vā pī⸱thaṁ vā bhi⸱siṁ vā koc⸱chaṁ vā aj⸱jho⸱kā⸱se san⸱tha⸱rit⸱vā vā san⸱tha⸱rā⸱pet⸱vā vā, "
 "siṭ"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "sma"____"ā⸱ya⸱sma⸱to kho pā⸱pa⸱kā sa⸱mā⸱cā⸱rā dis⸱san⸱ti c’e⸱va suy⸱yan⸱ti ca, "
 "sman"____"i⸱ti e⸱vaṁ sab⸱be⸱hi ā⸱ya⸱sman⸱te⸱hi u⸱tuk⸱khā⸱naṁ  dhā⸱re⸱tab⸱baṁ.                              ("
 "smi"____"a⸱ha⸱ma⸱smi sam⸱mā pa⸱ṭi⸱pan⸱no, "
 "smiñ"____"a⸱yaṁ he⸱man⸱to⸱tu a⸱smiñ⸱ca u⸱tum⸱hi aṭ⸱ṭha u⸱po⸱sa⸱thā,  "
 "smiṁ"____"bhik⸱khu⸱ga⸱ṇa⸱nā nā⸱ma i⸱ma⸱smiṁ u⸱po⸱sa⸱thag⸱ge  "
 "smā"____"ta⸱smā sa⸱ra⸱mā⸱ne⸱na bhik⸱khu⸱nā ā⸱pan⸱ne⸱na vi⸱sud⸱dhā⸱pek⸱khe⸱na san⸱tī ā⸱pat⸱ti ā⸱vi⸱kā⸱tab⸱bā, "
 "som"____"som⸱hi e⸱ta⸱ra⸱hi a⸱hut⸱vā san⸱ta⸱tā⸱ya pa⸱ri⸱ṇa⸱to⸱’ti. "
 "sos"____"yaṁ i⸱me bha⸱ṇis⸱san⸱ti taṁ sos⸱sā⸱mī”"
 "ssa"____"i⸱ti⸱’ssa mu⸱hut⸱tam⸱’pi a⸱phā⸱su bha⸱vis⸱sa⸱tī”"
 "sub"____"sub⸱rah⸱mā pa⸱ra⸱mat⸱to ca "
 "sud"____"te⸱sañ⸱ñe⸱va a⸱ka⸱tu⸱po⸱sa⸱thā⸱naṁ pā⸱ri⸱sud⸱dhi⸱yā⸱pi ā⸱ha⸱ra⸱ṇañ⸱ca;          "
 "suddh"____"pa⸱ri⸱suddh’ etth’ ā⸱ya⸱sman⸱to, "
 "suk"____"sañ⸱ce⸱ta⸱ni⸱kā suk⸱ka⸱vi⸱saṭ⸱ṭhi añ⸱ñat⸱ra su⸱pi⸱nan⸱tā saṅ⸱ghā⸱di⸱se⸱so.   2. "
 "sup"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "sut"____"yo pa⸱na bhik⸱khu sā⸱maṁ sut⸱taṁ viñ⸱ñā⸱pet⸱vā tan⸱ta⸱vā⸱ye⸱hi cī⸱va⸱raṁ vā⸱yā⸱pey⸱ya, "
 "suy"____"tas⸱sa kho pā⸱pa⸱kā sa⸱mā⸱cā⸱rā dis⸱san⸱ti c’e⸱va suy⸱yan⸱ti ca, "
 "suñ"____"bhik⸱khu⸱pe⸱suñ⸱ñe pā⸱cit⸱ti⸱yaṁ.    4. "
 "suṁ"____"ye⸱’pi te bhik⸱kha⸱ve a⸱he⸱suṁ a⸱tī⸱ta⸱m-ad⸱dhā⸱naṁ a⸱ra⸱han⸱to sam⸱mā-sam⸱bud⸱dhā, "
 "syā"____"syā. "
 "tab"____"u⸱po⸱sa⸱tha⸱ka⸱ra⸱ṇa⸱to pub⸱be  na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ kā⸱tab⸱baṁ ho⸱ti:          "
 "tac"____"i⸱daṁ kho ā⸱vu⸱so ci⸱va⸱raṁ maṁ ud⸱dis⸱sa vī⸱ya⸱ti ā⸱ya⸱tañ⸱ca ka⸱ro⸱tha vit⸱tha⸱tañ⸱ca ap⸱pi⸱tañ⸱ca su⸱vi⸱tañ⸱ca su⸱pa⸱vā⸱yi⸱tañ⸱ca su⸱vi⸱lek⸱khi⸱tañ⸱ca su⸱vi⸱tac⸱chi⸱tañ⸱ca ka⸱ro⸱tha; "
 "tad"____"ti e⸱tad⸱’ e⸱va pac⸱ca⸱yaṁ ka⸱rit⸱vā a⸱nañ⸱ñaṁ, "
 "tag"____"aj⸱ja⸱tag⸱ge te ā⸱vu⸱so sa⸱ma⸱ṇud⸱de⸱sa na c’e⸱va so bha⸱ga⸱vā sat⸱thā a⸱pa⸱di⸱si⸱tab⸱bo yam⸱’pi c’añ⸱ñe sa⸱ma⸱ṇud⸱de⸱sā la⸱bhan⸱ti bhik⸱khū⸱hi sad⸱dhiṁ dvi⸱rat⸱ta⸱ti⸱rat⸱taṁ sa⸱ha⸱sey⸱yaṁ, "
 "tak"____"añ⸱ñe⸱va dham⸱mā gam⸱bhī⸱rā dud⸱da⸱sā du⸱ra⸱nu⸱bo⸱dhā san⸱tā pa⸱ṇī⸱tā a⸱tak⸱kā⸱va⸱ca⸱rā ni⸱pu⸱ṇā paṇ⸱ḍi⸱ta⸱ve⸱da⸱nī⸱yā, "
 "tam"____"tam⸱’ e⸱naṁ sad⸱dhe⸱ya⸱va⸱ca⸱sā u⸱pā⸱si⸱kā dis⸱vā tiṇ⸱ṇaṁ dham⸱mā⸱naṁ añ⸱ña⸱ta⸱re⸱na va⸱dey⸱ya pā⸱rā⸱ji⸱ke⸱na vā saṅ⸱ghā⸱di⸱se⸱se⸱na vā pā⸱cit⸱ti⸱ye⸱na vā. "
 "tan"____"ma⸱tan⸱te jī⸱vi⸱tā sey⸱yo” "
 "tap"____"te ca ā⸱tap⸱pa⸱m-a⸱ka⸱ruṁ "
 "tas"____"na⸱mo tas⸱sa bha⸱ga⸱va⸱to a⸱ra⸱ha⸱to sam⸱mā sam⸱bhud⸱dhas⸱sa. ("
 "tat"____"tat⸱tha pa⸱dī⸱puj⸱ja⸱la⸱nañ⸱ca;          "
 "tathe"____"e⸱vañ⸱ca so bhik⸱khu bhik⸱khū⸱hi vuc⸱ca⸱mā⸱no tath’e⸱va pag⸱gaṇ⸱hey⸱ya, "
 "tatr"____"tatr’ i⸱daṁ pa⸱mā⸱naṁ. "
 "tatth"____"tatth’ ā⸱ya⸱sman⸱te puc⸱chā⸱mi : "
 "tañ"____"tañ⸱ce añ⸱ñā⸱ta⸱ko ga⸱ha⸱pa⸱ti vā ga⸱ha⸱pa⸱tā⸱nī vā ba⸱hū⸱hi cī⸱va⸱re⸱hi a⸱bhi⸱haṭ⸱ṭhuṁ pa⸱vā⸱rey⸱ya, "
 "taṁ"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "taṅ"____"na⸱vaṁ pa⸱na bhik⸱khu⸱nā mañ⸱caṁ vā pī⸱ṭhaṁ vā kā⸱ra⸱ya⸱mā⸱ne⸱na aṭ⸱ṭhaṅ⸱gu⸱la⸱pā⸱da⸱kaṁ kā⸱re⸱tab⸱baṁ su⸱ga⸱taṅ⸱gu⸱le⸱na añ⸱ñat⸱ra het⸱thi⸱mā⸱ya a⸱ṭa⸱ni⸱yā, "
 "taṇ"____"taṇ⸱ṭhā⸱na⸱sam⸱maj⸱ja⸱nañ⸱ca;         "
 "tel"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "tey"____"pa⸱ṭha⸱mo mā⸱so ic⸱c’e⸱te aḍ⸱ḍha⸱tey⸱ya⸱mā⸱sā uṇ⸱ha⸱sa⸱ma⸱yo, "
 "thab"____"tā⸱va⸱ti⸱haṁ te⸱na bhik⸱khu⸱nā a⸱kā⸱mā pa⸱ri⸱vat⸱thab⸱baṁ, "
 "thag"____"bhik⸱khu⸱ga⸱ṇa⸱nā nā⸱ma i⸱ma⸱smiṁ u⸱po⸱sa⸱thag⸱ge  "
 "than"____"i⸱mi⸱nā cī⸱va⸱ra⸱ce⸱tā⸱pa⸱ne⸱na cī⸱va⸱raṁ ce⸱tā⸱pet⸱vā it⸱than⸱nā⸱maṁ bhik⸱khuṁ cī⸱va⸱re⸱na ac⸱chā⸱des⸱sā⸱mī”"
 "that"____"u⸱po⸱sa⸱that⸱thā⸱ya san⸱ni⸱pa⸱ti⸱tā bhik⸱khū et⸱ta⸱kā⸱ti bhik⸱khū⸱naṁ ga⸱ṇa⸱nā,   "
 "thaṁ"____"saṅ⸱gho u⸱po⸱sa⸱thaṁ ka⸱rey⸱ya pā⸱ṭi⸱mok⸱khaṁ ud⸱di⸱sey⸱ya.   "
 "thaṅ"____"sam⸱ma⸱to⸱’pi ce bhik⸱khu at⸱thaṅ⸱ga⸱te su⸱ri⸱ye bhik⸱khu ni⸱yo o⸱va⸱dey⸱ya, "
 "they"____"yo pa⸱na bhik⸱khu gā⸱mā vā a⸱rañ⸱ñā vā a⸱din⸱naṁ they⸱ya⸱saṅ⸱khā⸱taṁ ā⸱di⸱yey⸱ya, "
 "thit"____"at⸱thit⸱ve⸱va sas⸱sa⸱ti⸱sa⸱maṁ. "
 "thiṁ"____"bhik⸱khu pu⸱rā⸱ṇa⸱san⸱tha⸱tas⸱sa sā⸱man⸱tā su⸱ga⸱ta⸱vi⸱dat⸱thiṁ na⸱vaṁ ni⸱sī⸱da⸱na⸱san⸱tha⸱taṁ kā⸱rā⸱pey⸱ya, "
 "thre"____"thre⸱e ti⸱mes.) ("
 "thuj"____"ye⸱na pu⸱thuj⸱ja⸱no ta⸱thā⸱ga⸱tas⸱sa vaṇ⸱ṇaṁ va⸱da⸱mā⸱no va⸱dey⸱ya. "
 "thuṁ"____"te⸱hi bhik⸱khū⸱hi vat⸱thuṁ de⸱se⸱tab⸱baṁ a⸱nā⸱ram⸱bhaṁ sa⸱pa⸱rik⸱ka⸱ma⸱naṁ. "
 "thāj"____"sa⸱ce so di⸱va⸱so cā⸱tud⸱da⸱si-paṇ⸱ṇa⸱ra⸱sī sā⸱mag⸱gī⸱na⸱mañ⸱ña⸱ta⸱ro ya⸱thāj⸱ja u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so,   "
 "tic"____"ma⸱hal⸱la⸱kaṁ pa⸱na bhik⸱khu⸱nā vi⸱hā⸱raṁ kā⸱ra⸱ya⸱mā⸱ne⸱na yā⸱va dvā⸱ra⸱ko⸱sā ag⸱ga⸱laṭ⸱ṭha⸱pa⸱nā⸱ya ā⸱lo⸱ka⸱san⸱dhi⸱pa⸱ri⸱kam⸱mā⸱ya dvit⸱tic⸱cha⸱da⸱nas⸱sa pa⸱ri⸱yā⸱yaṁ ap⸱pa⸱ha⸱ri⸱te ṭhi⸱te⸱na a⸱dhiṭ⸱ṭhā⸱tab⸱baṁ, "
 "tik"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "tim"____"tim⸱ba⸱rū su⸱ri⸱ya⸱vac⸱cha⸱sā "
 "tis"____"bhik⸱khuṁ pa⸱n’e⸱va ud⸱dis⸱sa añ⸱ñā⸱ta⸱kas⸱sa ga⸱ha⸱pa⸱tis⸱sa vā ga⸱ha⸱pa⸱tā⸱ni⸱yā vā cī⸱va⸱ra⸱ce⸱tā⸱pa⸱naṁ u⸱pak⸱kha⸱ṭaṁ ho⸱ti, “"
 "tit"____"sa⸱ma⸱tit⸱ti⸱kaṁ piṇ⸱ḍa⸱pā⸱taṁ pa⸱ṭig⸱ga⸱hes⸱sā⸱mī⸱’ti, "
 "tiṁ"____"yo pa⸱na bhik⸱khu yā⸱va⸱ta⸱ti⸱yaṁ a⸱nus⸱sā⸱vi⸱ya⸱mā⸱ne sa⸱ra⸱mā⸱no san⸱tiṁ ā⸱pat⸱tiṁ n’ā⸱vi⸱ka⸱rey⸱ya, "
 "tiṇ"____"yo pa⸱na bhik⸱khu o⸱tiṇ⸱ṇo vi⸱pa⸱ri⸱ṇa⸱te⸱na cit⸱te⸱na mā⸱tu⸱gā⸱me⸱na sad⸱dhiṁ kā⸱ya⸱saṁ⸱sag⸱gaṁ sa⸱mā⸱paj⸱jey⸱ya, "
 "tiṭ"____"bhik⸱khu ca do⸱saṁ pa⸱tiṭ⸱ṭhā⸱’ ti, "
 "tres"____"ju⸱squ⸱’i⸱ci fixed ma⸱nu⸱el⸱le⸱ment = ju⸱squ⸱’i⸱ci  pe⸱ut con⸱te⸱nir des let⸱tres sup⸱pri⸱mée⸱s ac⸱ci⸱den⸱tel⸱le⸱ment) "
 "ttha"____"kac⸱ci⸱’ ttha pa⸱ri⸱sud⸱dhā? "
 "tuc"____"tuc⸱chaṁ mu⸱sā vi⸱la⸱pin”"
 "tud"____"sa⸱ce so di⸱va⸱so cā⸱tud⸱da⸱si-paṇ⸱ṇa⸱ra⸱sī sā⸱mag⸱gī⸱na⸱mañ⸱ña⸱ta⸱ro ya⸱thāj⸱ja u⸱po⸱sa⸱tho paṇ⸱ṇa⸱ra⸱so,   "
 "tuk"____"u⸱tuk⸱khā⸱nañ⸱ca;          "
 "tum"____"a⸱yaṁ he⸱man⸱to⸱tu a⸱smiñ⸱ca u⸱tum⸱hi aṭ⸱ṭha u⸱po⸱sa⸱thā,  "
 "tun"____"a⸱tha kho ca⸱tun⸱naṁ sud⸱dhā⸱vā⸱sa-kā⸱yi⸱kā⸱naṁ de⸱vā⸱naṁ e⸱ta⸱d-a⸱ho⸱si, “"
 "tut"____"ta⸱ti⸱yaṁ o⸱dā⸱tā⸱naṁ ca⸱tut⸱thaṁ go⸱ca⸱ri⸱yā⸱naṁ. "
 "tuyh"____"pu⸱ri⸱sa kiṁ tuyh’ i⸱mi⸱nā pā⸱pa⸱ke⸱na duj⸱jī⸱vi⸱te⸱na? "
 "tuṁ"____"kā⸱tuṁ yut⸱ta⸱rū⸱paṁ.   "
 "tuṇ"____"a⸱san⸱ti⸱yā ā⸱pat⸱ti⸱yā tuṇ⸱hī bha⸱vi⸱tab⸱baṁ,  "
 "tva"____"mic⸱chā pa⸱ṭi⸱pan⸱no tva⸱ma⸱si, "
 "tvaṁ"____"yaṁ tvaṁ pā⸱ṭi⸱mok⸱khe ud⸱dis⸱sa⸱mā⸱ne na sā⸱dhu⸱kaṁ aṭ⸱ṭhi⸱kat⸱vā ma⸱na⸱si⸱ka⸱ro⸱sī”"
 "tāḷ"____"pat⸱tāḷ⸱ha⸱kaṁ ra⸱tha⸱kaṁ dha⸱nu⸱kaṁ ak⸱kha⸱ri⸱kaṁ ma⸱ne⸱si⸱kaṁ ya⸱thā⸱vaj⸱jaṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā jū⸱tap⸱pa⸱mā⸱daṭ⸱ṭhā⸱nā⸱nu⸱yo⸱gā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "ub"____"niṭ⸱ṭhi⸱ta⸱cī⸱va⸱ra⸱smiṁ bhik⸱khu⸱nā ub⸱bha⸱ta⸱smiṁ ka⸱ṭhi⸱ne, "
 "uc"____"na nī⸱ce ā⸱sa⸱ne ni⸱sī⸱dit⸱vā uc⸱ce ā⸱sa⸱ne ni⸱sin⸱nas⸱sa a⸱gi⸱lā⸱nas⸱sa dham⸱maṁ de⸱sis⸱sā⸱mī⸱’ti, "
 "ud"____"saṅ⸱gho u⸱po⸱sa⸱thaṁ ka⸱rey⸱ya pā⸱ṭi⸱mok⸱khaṁ ud⸱di⸱sey⸱ya.   "
 "ug"____"yo pa⸱na bhik⸱khu jā⸱ta⸱rū⸱pa⸱ra⸱ja⸱taṁ ug⸱gaṇ⸱hey⸱ya vā ug⸱gaṇ⸱hā⸱pey⸱ya vā u⸱pa⸱nik⸱khit⸱taṁ vā sā⸱di⸱yey⸱ya, "
 "uj"____"uj⸱jhā⸱pa⸱na⸱ke khiy⸱ya⸱na⸱ke pā⸱cit⸱ti⸱yaṁ.    14. "
 "uk"____"yo pa⸱na bhik⸱khu jā⸱naṁ ya⸱thā⸱dham⸱maṁ ni⸱ha⸱tā⸱dhi⸱ka⸱ra⸱ṇaṁ pu⸱na⸱kam⸱mā⸱ya uk⸱ko⸱ṭey⸱ya, "
 "um"____"um⸱mā-pup⸱pha⸱ni⸱bhā⸱si⸱no "
 "up"____"bhik⸱khu⸱no pa⸱n’e⸱va a⸱kā⸱la⸱cī⸱va⸱raṁ up⸱paj⸱jey⸱ya, "
 "ut"____"yo pa⸱na bhik⸱khu a⸱na⸱bhi⸱jā⸱naṁ ut⸱ta⸱ri⸱ma⸱nus⸱sa⸱dham⸱maṁ at⸱tū⸱pa⸱nā⸱yi⸱kaṁ   "
 "uy"____"tas⸱sa dā⸱pet⸱vā vā a⸱dā⸱pet⸱vā vā uy⸱yo⸱jey⸱ya “gacch’ ā⸱vu⸱so, "
 "uṁ"____"a⸱lañ⸱ca kho ho⸱ti mā⸱tu⸱gā⸱maṁ duṭ⸱ṭhul⸱lā⸱hi vā⸱cā⸱hi o⸱bhā⸱si⸱uṁ. "
 "uṇ"____"pa⸱ṭha⸱mo mā⸱so ic⸱c’e⸱te aḍ⸱ḍha⸱tey⸱ya⸱mā⸱sā uṇ⸱ha⸱sa⸱ma⸱yo, "
 "uṭ"____"yo pa⸱na bhik⸱khu saṅ⸱ghe vi⸱nic⸱cha⸱ya⸱ka⸱thā⸱ya vat⸱ta⸱mā⸱nā⸱ya chan⸱daṁ a⸱dat⸱vā uṭ⸱ṭhā⸱yā⸱sa⸱nā pak⸱ka⸱mey⸱ya, "
 "vac"____"at⸱thi pa⸱n’ā⸱ya⸱sma⸱to ko⸱ci vey⸱yā⸱vac⸱ca⸱ka⸱ro”"
 "vad"____"e⸱vaṁ saṁ⸱vad⸱dhā  "
 "vag"____"tas⸱s’e⸱va kho pa⸱na bhik⸱khus⸱sa bhik⸱khū hon⸱ti a⸱nu⸱vat⸱ta⸱kā vag⸱ga⸱vā⸱da⸱kā, "
 "vaj"____"te⸱sañ⸱ca  hat⸱tha⸱pā⸱se  hat⸱tha⸱pā⸱sa⸱to ba⸱hi⸱ka⸱ra⸱ṇa⸱va⸱se⸱na vaj⸱je⸱tab⸱bo ko⸱ci vaj⸱ja⸱nī⸱ya⸱pug⸱ga⸱lo ce nat⸱thi.   "
 "vak"____"a⸱hamp’ ā⸱ya⸱sman⸱te na kiñ⸱ci vak⸱khā⸱mi kal⸱yā⸱ṇaṁ vā pā⸱pa⸱kaṁ vā, "
 "vam"____"e⸱vam⸱’ e⸱taṁ dhā⸱ra⸱yā⸱mi. ("
 "van"____"i⸱ti sa⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ ka⸱tat⸱tā nik⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ pa⸱ka⸱ti⸱yā pa⸱ri⸱niṭ⸱ṭhi⸱tat⸱tā e⸱van⸱taṁ na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ pa⸱ri⸱niṭ⸱ṭhi⸱taṁ ho⸱ti.   "
 "vas"____"u⸱tū⸱nī⸱dha pa⸱na sā⸱sa⸱ne he⸱man⸱ta-gim⸱ha-vas⸱sā⸱nā⸱naṁ va⸱se⸱na tī⸱ṇi hon⸱ti.   "
 "vat"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "vañ"____"e⸱vañ⸱ca so bhik⸱khu bhik⸱khū⸱hi vuc⸱ca⸱mā⸱no tath’e⸱va pag⸱gaṇ⸱hey⸱ya, "
 "vaḍ"____"yo pa⸱na bhik⸱khu an⸱vaḍ⸱ḍha⸱mā⸱saṁ pā⸱ṭi⸱mok⸱khe ud⸱dis⸱sa⸱mā⸱ne e⸱vaṁ va⸱dey⸱ya, “"
 "vaṁ"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "vaṁa"____"i⸱me diṭ⸱ṭhiṭ⸱ṭhā⸱nā e⸱vaṁ⸱ga⸱hi⸱tā e⸱vaṁ⸱pa⸱rā⸱maṭ⸱ṭhā e⸱vaṁ⸱ga⸱ti⸱kā bha⸱van⸱ti e⸱vaṁa⸱bhi⸱sam⸱pa⸱rā⸱yā⸱’ti, "
 "vaṅ"____"aṭ⸱ṭha⸱pa⸱daṁ da⸱sa⸱pa⸱daṁ ā⸱kā⸱saṁ pa⸱ri⸱hā⸱ra⸱pa⸱thaṁ san⸱ti⸱kaṁ kha⸱li⸱kaṁ gha⸱ṭi⸱kaṁ sa⸱lā⸱ka⸱hat⸱thaṁ ak⸱khaṁ paṅ⸱ga⸱cī⸱raṁ vaṅ⸱ka⸱kaṁ mok⸱kha⸱ci⸱kaṁ ciṅ⸱gu⸱li⸱kaṁ {"
 "vaṇ"____"ma⸱ra⸱ṇa⸱vaṇ⸱ṇaṁ vā saṁ⸱vaṇ⸱ṇey⸱ya, "
 "vaṭ"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ti⸱kā⸱ya bhik⸱khu⸱ni⸱yā hat⸱tha⸱to cī⸱va⸱raṁ pa⸱ṭig⸱gaṇ⸱hey⸱ya añ⸱ñat⸱ra pā⸱ri⸱vaṭ⸱ṭa⸱kā, "
 "ves"____"ves⸱sā⸱mit⸱tā pañ⸱ca-sa⸱tā "
 "vey"____"vey⸱yā⸱ka⸱ra⸱ṇaṁ ho⸱ti, "
 "veṇ"____"veṇ⸱ḍū ca de⸱vā sa⸱ha⸱lī ca "
 "veṭ"____"na veṭ⸱ṭhi⸱ta⸱sī⸱sas⸱sa a⸱gi⸱lā⸱nas⸱sa dham⸱maṁ de⸱sis⸱sā⸱mī⸱’ti, "
 "vic"____"khet⸱ta⸱vij⸱jā (ba⸱hū⸱su)} si⸱va⸱vij⸱jā bhū⸱ta⸱vij⸱jā bhū⸱ri⸱vij⸱jā a⸱hi⸱vij⸱jā vi⸱sa⸱vij⸱jā vic⸱chi⸱ka⸱vij⸱jā mū⸱si⸱ka⸱vij⸱jā sa⸱ku⸱ṇa⸱vij⸱jā vā⸱ya⸱sa⸱vij⸱jā pak⸱kaj⸱jhā⸱naṁ sa⸱ra⸱pa⸱rit⸱tā⸱ṇaṁ mi⸱ga⸱cak⸱kaṁ i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "vig"____"yo pa⸱na bhik⸱khu sañ⸱cic⸱ca ma⸱nus⸱sa⸱vig⸱ga⸱haṁ jī⸱vi⸱tā vo⸱ro⸱pey⸱ya,  "
 "vij"____"te⸱sañ⸱ca vi⸱kā⸱la⸱bho⸱ja⸱nā⸱di⸱va⸱se⸱na vat⸱thu⸱sa⸱bhā⸱gā⸱pat⸱ti⸱yo ce na vij⸱jan⸱ti, "
 "vik"____"yo pa⸱na bhik⸱khu nā⸱nap⸱pa⸱kā⸱ra⸱kaṁ ka⸱ya⸱vik⸱ka⸱yaṁ sa⸱mā⸱paj⸱jey⸱ya, "
 "vip"____"e⸱ka⸱rat⸱tam⸱’pi ce bhik⸱khu ti⸱cī⸱va⸱re⸱na vip⸱pa⸱va⸱sey⸱ya, "
 "vis"____"o⸱re⸱na ce chan⸱naṁ vas⸱sā⸱naṁ taṁ san⸱tha⸱taṁ vis⸱saj⸱jet⸱vā vā a⸱vis⸱saj⸱jet⸱vā vā añ⸱ñaṁ na⸱vaṁ san⸱tha⸱taṁ kā⸱rā⸱pey⸱ya añ⸱ñat⸱ra bhik⸱khu⸱sam⸱ma⸱ti⸱yā, "
 "vit"____"i⸱daṁ kho ā⸱vu⸱so ci⸱va⸱raṁ maṁ ud⸱dis⸱sa vī⸱ya⸱ti ā⸱ya⸱tañ⸱ca ka⸱ro⸱tha vit⸱tha⸱tañ⸱ca ap⸱pi⸱tañ⸱ca su⸱vi⸱tañ⸱ca su⸱pa⸱vā⸱yi⸱tañ⸱ca su⸱vi⸱lek⸱khi⸱tañ⸱ca su⸱vi⸱tac⸱chi⸱tañ⸱ca ka⸱ro⸱tha; "
 "viñ"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ta⸱kaṁ ga⸱ha⸱pa⸱tiṁ vā ga⸱ha⸱pa⸱tā⸱niṁ vā cī⸱va⸱raṁ viñ⸱ñā⸱pey⸱ya añ⸱ñat⸱ra sa⸱ma⸱yā, "
 "viṁ"____"yo pa⸱na bhik⸱khu pa⸱ṭha⸱viṁ kha⸱ṇey⸱ya vā kha⸱ṇā⸱pey⸱ya vā, "
 "viṭ"____"yo pa⸱na bhik⸱khu añ⸱ñā⸱ti⸱kā⸱ya bhik⸱khu⸱ni⸱yā an⸱ta⸱ra⸱gha⸱raṁ pa⸱viṭ⸱ṭhā⸱ya hat⸱tha⸱to khā⸱da⸱nī⸱yaṁ vā bho⸱ja⸱nī⸱yaṁ vā sa⸱hat⸱thā pa⸱ṭig⸱ga⸱het⸱vā khā⸱dey⸱ya vā bhuñ⸱jey⸱ya vā. "
 "vos"____"san⸱ti⸱kam⸱maṁ pa⸱ṇi⸱dhi⸱kam⸱maṁ bhū⸱ta⸱kam⸱maṁ bhū⸱ri⸱kam⸱maṁ vas⸱sa⸱kam⸱maṁ vos⸱sa⸱kam⸱maṁ vat⸱thu⸱kam⸱maṁ vat⸱thu⸱pa⸱ri⸱kam⸱maṁ ā⸱ca⸱ma⸱naṁ nhā⸱pa⸱naṁ ju⸱ha⸱naṁ va⸱ma⸱naṁ vi⸱re⸱ca⸱naṁ ud⸱dhaṁ⸱vi⸱re⸱ca⸱naṁ a⸱dho⸱vi⸱re⸱ca⸱naṁ sī⸱sa⸱vi⸱re⸱ca⸱naṁ kaṇ⸱ṇa⸱te⸱laṁ net⸱ta⸱tap⸱pa⸱naṁ nat⸱thu⸱kam⸱maṁ añ⸱ja⸱naṁ pac⸱cañ⸱ja⸱naṁ sā⸱lā⸱ki⸱yaṁ sal⸱la⸱kat⸱ti⸱yaṁ dā⸱ra⸱ka⸱ti⸱kic⸱chā mū⸱la⸱bhe⸱saj⸱jā⸱naṁ a⸱nup⸱pa⸱dā⸱naṁ o⸱sa⸱dhī⸱naṁ pa⸱ṭi⸱mok⸱kho i⸱ti vā i⸱ti e⸱va⸱rū⸱pā⸱ya ti⸱rac⸱chā⸱na⸱vij⸱jā⸱ya mic⸱chā⸱jī⸱vā pa⸱ṭi⸱vi⸱ra⸱to sa⸱ma⸱ṇo go⸱ta⸱mo⸱’ti — "
 "vuc"____"e⸱vañ⸱ca so bhik⸱khu bhik⸱khū⸱hi vuc⸱ca⸱mā⸱no tath’e⸱va pag⸱gaṇ⸱hey⸱ya, "
 "vus"____"ya⸱thā pā⸱vus⸱sa⸱ko me⸱gho "
 "vut"____"sam⸱pa⸱jā⸱na⸱mu⸱sā⸱vā⸱do kho pa⸱n’ā⸱ya⸱sman⸱to an⸱ta⸱rā⸱yi⸱ko dham⸱mo vut⸱to bha⸱ga⸱va⸱tā.  "
 "vuṭ"____"hi tas⸱sa bha⸱ga⸱va⸱to pa⸱ri⸱sā ya⸱d’i⸱daṁ añ⸱ña⸱mañ⸱ña⸱va⸱ca⸱ne⸱na añ⸱ña⸱mañ⸱ña⸱vuṭ⸱ṭhā⸱pa⸱ne⸱nā”"
 "vās"____"sat⸱tha⸱hā⸱ra⸱kaṁ vās⸱sa pa⸱ri⸱ye⸱sey⸱ya, "
 "yag"____"sū⸱ri⸱yag⸱gā⸱ho {"
 "yak"____"sat⸱ta-sa⸱has⸱sā va yak⸱khā "
 "yam"____"a⸱yam⸱’pi pā⸱rā⸱ji⸱ko ho⸱ti a⸱saṁ⸱vā⸱so.   3. "
 "yan"____"ap⸱p’e⸱va nā⸱ma naṁ i⸱mam⸱hā brah⸱ma⸱ca⸱ri⸱yā cā⸱vey⸱yan” "
 "yap"____"na kā⸱yap⸱pa⸱cā⸱la⸱kaṁ an⸱ta⸱ra⸱gha⸱re ga⸱mis⸱sā⸱mī⸱’ti, "
 "yas"____"yas⸱sa si⸱yā ā⸱pat⸱ti, "
 "yat"____"yo pa⸱na bhik⸱khu sañ⸱ca⸱rit⸱taṁ sa⸱mā⸱paj⸱jey⸱ya it⸱thi⸱yā vā pu⸱ri⸱sa⸱ma⸱tiṁ pu⸱ri⸱sas⸱sa vā it⸱thī⸱ma⸱tiṁ jā⸱yat⸱ta⸱ne vā jā⸱rat⸱ta⸱ne vā an⸱ta⸱ma⸱so taṁ kha⸱ṇi⸱kā⸱ya⸱’ pi, "
 "yath"____"sey⸱yath⸱’ ī⸱daṁ, "
 "yathī"____"sey⸱yath’ī⸱daṁ : "
 "yañ"____"añ⸱ña⸱bhā⸱gi⸱yañ c’e⸱va taṁ a⸱dhi⸱ka⸱ra⸱ṇaṁ ho⸱ti, "
 "yaḍ"____"di⸱yaḍ⸱ḍho mā⸱so se⸱so gim⸱hā⸱nan⸱’ti, "
 "yaṁ"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "yaṅ"____"yā sā vā⸱cā ne⸱lā kaṇ⸱ṇa⸱su⸱khā pe⸱ma⸱nī⸱yā ha⸱da⸱yaṅ⸱ga⸱mā po⸱rī ba⸱hu⸱ja⸱na⸱kan⸱tā ba⸱hu⸱ja⸱na⸱ma⸱nā⸱pā ta⸱thā⸱rū⸱piṁ vā⸱caṁ bhā⸱si⸱tā⸱’ti — "
 "yey"____"yo pa⸱na bhik⸱khu gā⸱mā vā a⸱rañ⸱ñā vā a⸱din⸱naṁ they⸱ya⸱saṅ⸱khā⸱taṁ ā⸱di⸱yey⸱ya, "
 "yim"____"te ma⸱yaṁ a⸱ti⸱ve⸱laṁ añ⸱ña⸱mañ⸱ñaṁ u⸱pa⸱nij⸱jhā⸱yim⸱hā. "
 "yis"____"kit⸱ta⸱yis⸱sā⸱mi bhik⸱kha⸱ve de⸱va-kā⸱yā⸱naṁ nā⸱mā⸱ni. "
 "yiṭ"____"sas⸱sa⸱to at⸱tā ca lo⸱ko ca vañ⸱jho kū⸱ṭaṭ⸱ṭho e⸱si⸱kaṭ⸱ṭhā⸱yiṭ⸱ṭhi⸱to; "
 "yud"____"caṇ⸱ḍā⸱laṁ vaṁ⸱saṁ dho⸱va⸱naṁ hat⸱thi⸱yud⸱dhaṁ as⸱sa⸱yud⸱dhaṁ ma⸱hiṁ⸱sa⸱yud⸱dhaṁ {"
 "yuk"____"a⸱tha kho añ⸱ña⸱ta⸱ro sat⸱to ā⸱yuk⸱kha⸱yā vā puñ⸱ñak⸱kha⸱yā vā ā⸱bhas⸱sa⸱ra⸱kā⸱yā ca⸱vit⸱vā suñ⸱ñaṁ brah⸱ma⸱vi⸱mā⸱naṁ u⸱pa⸱paj⸱ja⸱ti. "
 "yun"____"a⸱ho va⸱ta añ⸱ñe⸱pi sat⸱tā it⸱that⸱taṁ ā⸱gac⸱chey⸱yun⸱’ti. "
 "yut"____"kā⸱tuṁ yut⸱ta⸱rū⸱paṁ.   "
 "yuñ"____"yuñ⸱jan⸱t’ā⸱ya⸱sman⸱to sa⸱kaṁ mā vo sa⸱kaṁ vi⸱nas⸱sī”"
 "yuṁ"____"ya⸱thā⸱rū⸱pe a⸱din⸱nā⸱dā⸱ne rā⸱jā⸱no co⸱raṁ ga⸱het⸱vā ha⸱ney⸱yuṁ vā ban⸱dhey⸱yuṁ vā pab⸱bā⸱jey⸱yuṁ vā, “"
 "ñaṁ"____"o⸱re⸱na ce chan⸱naṁ vas⸱sā⸱naṁ taṁ san⸱tha⸱taṁ vis⸱saj⸱jet⸱vā vā a⸱vis⸱saj⸱jet⸱vā vā añ⸱ñaṁ na⸱vaṁ san⸱tha⸱taṁ kā⸱rā⸱pey⸱ya añ⸱ñat⸱ra bhik⸱khu⸱sam⸱ma⸱ti⸱yā, "
 "ñiṁ"____"e⸱ke sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā ud⸱dha⸱mā⸱ghā⸱ta⸱ni⸱kā sañ⸱ñī⸱vā⸱dā ud⸱dha⸱mā⸱ghā⸱ta⸱naṁ sañ⸱ñiṁ at⸱tā⸱naṁ pañ⸱ña⸱pen⸱ti so⸱ḷa⸱sa⸱hi vat⸱thū⸱hi. "
 "ñna"____"u⸱pa⸱vas⸱saṁ kho pa⸱na kat⸱ti⸱ka⸱puṇ⸱ṇa⸱maṁ yā⸱ni kho pa⸱na tā⸱ni ā⸱rañ⸱ñna⸱kā⸱ni se⸱nā⸱sa⸱nā⸱ni sā⸱saṅ⸱ka⸱sam⸱ma⸱tā⸱ni sap⸱pa⸱ṭi⸱bha⸱yā⸱ni ta⸱thā⸱rū⸱pe⸱su bhik⸱khu se⸱nā⸱sa⸱ne⸱su vi⸱ha⸱ran⸱to ā⸱kaṅ⸱kha⸱mā⸱no tiṇ⸱ṇaṁ cī⸱va⸱rā⸱naṁ añ⸱ña⸱ta⸱raṁ cī⸱va⸱raṁ an⸱ta⸱ra⸱gha⸱re nik⸱khi⸱pey⸱ya, "
 "ñāṇ"____"na ca tas⸱sa bhik⸱khu⸱no añ⸱ñāṇ⸱na⸱ke⸱na mut⸱ti at⸱thi: "
 "ḍa"____"e⸱vañ⸱ca so bhik⸱khu vat⸱vā kiñ⸱ci⸱mat⸱taṁ a⸱nu⸱pa⸱daj⸱jey⸱ya an⸱ta⸱ma⸱so piṇ⸱ḍa⸱pā⸱ta⸱mat⸱tam⸱’pi, "
 "ḍaṁ"____"mu⸱kha⸱cuṇ⸱ṇaṁ mu⸱kha⸱le⸱pa⸱naṁ hat⸱tha⸱ban⸱dhaṁ si⸱khā⸱ban⸱dhaṁ daṇ⸱ḍaṁ nā⸱ḷi⸱kaṁ a⸱siṁ {"
 "ḍes"____"na sa⸱sit⸱tha⸱kaṁ pat⸱ta⸱dho⸱va⸱naṁ an⸱ta⸱ra⸱gha⸱re chaḍ⸱ḍes⸱sā⸱mī⸱’ti, "
 "ḍha"____"aḍ⸱ḍha⸱mā⸱so se⸱so gim⸱hā⸱nan⸱’ti, "
 "ḍhaṁ"____"ti⸱ri⸱yaṁ di⸱yaḍ⸱ḍhaṁ, "
 "ḍhey"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ ku⸱pi⸱to a⸱nat⸱ta⸱ma⸱no saṅ⸱ghi⸱kā vi⸱hā⸱rā nik⸱kaḍ⸱ḍhey⸱ya vā nik⸱kaḍ⸱ḍhā⸱pey⸱ya vā, "
 "ḍho"____"di⸱yaḍ⸱ḍho mā⸱so se⸱so gim⸱hā⸱nan⸱’ti, "
 "ḍhā"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ ku⸱pi⸱to a⸱nat⸱ta⸱ma⸱no saṅ⸱ghi⸱kā vi⸱hā⸱rā nik⸱kaḍ⸱ḍhey⸱ya vā nik⸱kaḍ⸱ḍhā⸱pey⸱ya vā, "
 "ḍi"____"in⸱dri⸱yā⸱ni rak⸱khan⸱ti paṇ⸱ḍi⸱tā⸱ti.”  "
 "ḍo"____"a⸱gi⸱lā⸱ne⸱na bhik⸱khu⸱nā e⸱ko ā⸱va⸱sa⸱tha⸱piṇ⸱ḍo bhuñ⸱ji⸱tab⸱bo, "
 "ḍu"____"kaṇ⸱ḍu⸱pa⸱ṭic⸱chā⸱diṁ pa⸱na bhik⸱khu⸱nā kā⸱ra⸱ya⸱mā⸱ne⸱na pa⸱mā⸱ṇi⸱kā kā⸱re⸱tab⸱bā; "
 "ḍuk"____"na piṇ⸱ḍuk⸱khe⸱pa⸱kaṁ bhuñ⸱jis⸱sā⸱mī⸱’ti, "
 "ḍā"____"kum⸱bhaṇ⸱ḍā⸱naṁ ā⸱dhi⸱pa⸱ti "
 "ḍū"____"veṇ⸱ḍū ca de⸱vā sa⸱ha⸱lī ca "
 "ḷa"____"yo pa⸱na bhik⸱khu sud⸱dha⸱kā⸱ḷa⸱kā⸱naṁ e⸱ḷa⸱ka⸱lo⸱mā⸱naṁ san⸱tha⸱taṁ kā⸱rā⸱pey⸱ya, "
 "ḷan"____"e⸱kaṁ sa⸱ma⸱yaṁ bha⸱ga⸱vā an⸱ta⸱rā ca rā⸱ja⸱ga⸱haṁ an⸱ta⸱rā ca nā⸱ḷan⸱daṁ ad⸱dhā⸱na⸱mag⸱gap⸱pa⸱ṭi⸱pan⸱no ho⸱ti ma⸱ha⸱tā bhik⸱khu⸱saṅ⸱ghe⸱na sad⸱dhiṁ pañ⸱ca⸱mat⸱te⸱hi bhik⸱khu⸱sa⸱te⸱hi. "
 "ḷaṁ"____"nā⸱ti⸱ma⸱han⸱taṁ ka⸱va⸱ḷaṁ ka⸱ris⸱sā⸱mī⸱’ti, "
 "ḷe"____"na a⸱nā⸱ha⸱te ka⸱va⸱ḷe mu⸱khad⸱vā⸱raṁ vi⸱va⸱ris⸱sā⸱mī⸱’ti, "
 "ḷi"____"mu⸱kha⸱cuṇ⸱ṇaṁ mu⸱kha⸱le⸱pa⸱naṁ hat⸱tha⸱ban⸱dhaṁ si⸱khā⸱ban⸱dhaṁ daṇ⸱ḍaṁ nā⸱ḷi⸱kaṁ a⸱siṁ {"
 "ḷo"____"na⸱ḷo rā⸱jā ja⸱no⸱sa⸱bho "
 "ḷu"____"mū⸱la⸱bī⸱jaṁ khan⸱dha⸱bī⸱jaṁ pha⸱ḷu⸱bī⸱jaṁ ag⸱ga⸱bī⸱jaṁ bī⸱ja⸱bī⸱ja⸱me⸱va pañ⸱ca⸱maṁ {"
 "ḷā"____"pa⸱ri⸱ḷā⸱ha⸱sa⸱ma⸱yo, "
 "ḷī"____"añ⸱ño at⸱tā dib⸱bo rū⸱pī kā⸱mā⸱va⸱ca⸱ro ka⸱ba⸱ḷī⸱kā⸱rā⸱hā⸱ra⸱bhak⸱kho. "
 "ṇa"____"u⸱po⸱sa⸱tha⸱ka⸱ra⸱ṇa⸱to pub⸱be  na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ kā⸱tab⸱baṁ ho⸱ti:          "
 "ṇab"____"ya⸱thā vā pa⸱ne⸱ke bhon⸱to sa⸱ma⸱ṇab⸱rāh⸱ma⸱ṇā sad⸱dhā⸱dey⸱yā⸱ni bho⸱ja⸱nā⸱ni bhuñ⸱jit⸱vā te e⸱va⸱rū⸱paṁ bī⸱ja⸱gā⸱ma⸱bhū⸱ta⸱gā⸱ma⸱sa⸱mā⸱ram⸱bhaṁ a⸱nu⸱yut⸱tā vi⸱ha⸱ran⸱ti, "
 "ṇan"____"yañ⸱ca kho i⸱daṁ vuc⸱ca⸱ti cit⸱tan⸱ti vā ma⸱no⸱ti vā viñ⸱ñā⸱ṇan⸱ti vā a⸱yaṁ at⸱tā nic⸱co dhu⸱vo sas⸱sa⸱to a⸱vi⸱pa⸱ri⸱ṇā⸱ma⸱dham⸱mo sas⸱sa⸱ti⸱sa⸱maṁ ta⸱the⸱va ṭhas⸱sa⸱tī⸱’ti. "
 "ṇas"____"yo pa⸱na bhik⸱khu bhik⸱khuṁ duṭ⸱ṭho do⸱so ap⸱pa⸱tī⸱to añ⸱ña⸱bhā⸱gi⸱yas⸱sa a⸱dhi⸱ka⸱ra⸱ṇas⸱sa kiñ⸱ci de⸱saṁ le⸱sa⸱mat⸱taṁ u⸱pā⸱dā⸱ya pā⸱rā⸱ji⸱ke⸱na dham⸱me⸱na a⸱nud⸱dhaṁ⸱sey⸱ya, “"
 "ṇañ"____"chan⸱dā⸱ra⸱hā⸱naṁ bhik⸱khū⸱naṁ chan⸱dā⸱ha⸱ra⸱ṇañ⸱ca;         "
 "ṇaṁ"____"vey⸱yā⸱ka⸱ra⸱ṇaṁ ho⸱ti, "
 "ṇe"____"e⸱van⸱taṁ u⸱po⸱sa⸱tha⸱kam⸱maṁ i⸱me⸱hi ca⸱tū⸱hi  lak⸱kha⸱ṇe⸱hi saṅ⸱ga⸱hi⸱taṁ pat⸱ta⸱kal⸱laṁ nā⸱ma ho⸱ti, "
 "ṇey"____"ma⸱ra⸱ṇa⸱vaṇ⸱ṇaṁ vā saṁ⸱vaṇ⸱ṇey⸱ya, "
 "ṇi"____"a⸱pa⸱rā⸱ni tī⸱ṇi bhik⸱khū⸱naṁ vat⸱taṁ jā⸱nan⸱te⸱hi ā⸱rā⸱mi⸱ke⸱hi⸱pi bhik⸱khū⸱hi⸱pi ka⸱tā⸱ni pa⸱ri⸱niṭ⸱ṭhi⸱tā⸱ni hon⸱ti.   "
 "ṇis"____"yaṁ i⸱me bha⸱ṇis⸱san⸱ti taṁ sos⸱sā⸱mī”"
 "ṇit"____"yaṁ kho tum⸱he ā⸱ya⸱sman⸱to bhik⸱khuṁ ud⸱dis⸱sa cī⸱va⸱ra⸱ce⸱tā⸱pa⸱naṁ pa⸱hi⸱ṇit⸱tha na tan⸱tas⸱sa bhik⸱khu⸱no kiñ⸱ci at⸱thaṁ a⸱nu⸱bho⸱ti, "
 "ṇiṁ"____"sa⸱hi⸱tā⸱naṁ vā a⸱nup⸱pa⸱dā⸱tā sa⸱mag⸱gā⸱rā⸱mo sa⸱mag⸱ga⸱ra⸱to sa⸱mag⸱ga⸱nan⸱dī sa⸱mag⸱ga⸱ka⸱ra⸱ṇiṁ vā⸱caṁ bhā⸱si⸱tā⸱’ti — "
 "ṇo"____"i⸱ti sa⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ ka⸱tat⸱tā nik⸱ka⸱ra⸱ṇo⸱kā⸱sā⸱naṁ pub⸱ba⸱kic⸱cā⸱naṁ pa⸱ka⸱ti⸱yā pa⸱ri⸱niṭ⸱ṭhi⸱tat⸱tā e⸱van⸱taṁ na⸱va⸱vi⸱dhaṁ pub⸱ba⸱kic⸱caṁ pa⸱ri⸱niṭ⸱ṭhi⸱taṁ ho⸱ti.   "
 "ṇud"____"sa⸱ma⸱ṇud⸱de⸱so⸱’pi ce e⸱vaṁ va⸱dey⸱ya, “"
 "ṇā"____"chan⸱dā⸱ha⸱ra⸱ṇa pā⸱ri⸱sud⸱dhi-a⸱ha⸱ra⸱ṇā⸱ni pa⸱na i⸱mis⸱saṁ sī⸱mā⸱yaṁ hat⸱tha⸱pā⸱saṁ vi⸱ja⸱hit⸱vā ni⸱sin⸱nā⸱naṁ bhik⸱khū⸱naṁ a⸱bhā⸱va⸱to nath⸱hi.   "
 "ṇī"____"yā⸱ni kho pa⸱na tā⸱ni pa⸱ṇī⸱ta⸱bho⸱ja⸱nā⸱ni, "
 "ṭaṁ"____"bhik⸱khuṁ pa⸱n’e⸱va ud⸱dis⸱sa añ⸱ñā⸱ta⸱kas⸱sa ga⸱ha⸱pa⸱tis⸱sa vā ga⸱ha⸱pa⸱tā⸱ni⸱yā vā cī⸱va⸱ra⸱ce⸱tā⸱pa⸱naṁ u⸱pak⸱kha⸱ṭaṁ ho⸱ti, “"
 "ṭey"____"yo pa⸱na bhik⸱khu jā⸱naṁ ya⸱thā⸱dham⸱maṁ ni⸱ha⸱tā⸱dhi⸱ka⸱ra⸱ṇaṁ pu⸱na⸱kam⸱mā⸱ya uk⸱ko⸱ṭey⸱ya, "
 "ṭeṇ"____"mā⸱yā ku⸱ṭeṇ⸱ḍu ve⸱ṭeṇ⸱ḍu "
 "ṭhan"____"u⸱tuk⸱khā⸱naṁ nā⸱ma et⸱ta⸱kaṁ a⸱tik⸱kan⸱taṁ et⸱ta⸱kaṁ a⸱va⸱siṭ⸱ṭhan⸱ti e⸱vaṁ u⸱tu-ā⸱cik⸱kha⸱naṁ;   "
 "ṭhas"____"ya⸱thā kho pa⸱na pac⸱ce⸱ka⸱puṭ⸱ṭhas⸱sa  "
 "ṭhaṁ"____"yo pa⸱na bhik⸱khu saṅ⸱ghi⸱ke vi⸱hā⸱re u⸱pa⸱ri⸱ve⸱hā⸱sa⸱ku⸱ṭi⸱yā ā⸱hac⸱ca⸱pā⸱da⸱kaṁ mañ⸱caṁ vā pī⸱ṭhaṁ vā a⸱bhi⸱ni⸱sī⸱dey⸱ya vā a⸱bhi⸱ni⸱paj⸱jey⸱ya vā, "
 "ṭhaṅ"____"na⸱vaṁ pa⸱na bhik⸱khu⸱nā mañ⸱caṁ vā pī⸱ṭhaṁ vā kā⸱ra⸱ya⸱mā⸱ne⸱na aṭ⸱ṭhaṅ⸱gu⸱la⸱pā⸱da⸱kaṁ kā⸱re⸱tab⸱baṁ su⸱ga⸱taṅ⸱gu⸱le⸱na añ⸱ñat⸱ra het⸱thi⸱mā⸱ya a⸱ṭa⸱ni⸱yā, "
 "ṭhey"____"yo pa⸱na bhik⸱khu sa⸱mag⸱gas⸱sa saṅ⸱ghas⸱sa bhe⸱dā⸱ya pa⸱rak⸱ka⸱mey⸱ya bhe⸱da⸱na⸱saṁ⸱vat⸱ta⸱ni⸱kaṁ vā a⸱dhi⸱ka⸱ra⸱ṇaṁ sa⸱mā⸱dā⸱ya pag⸱gay⸱ha tiṭ⸱ṭhey⸱ya, "
 "ṭhiṁ"____"yo pa⸱na bhik⸱khu jā⸱naṁ ta⸱thā⸱vā⸱di⸱nā bhi⸱khu⸱nā a⸱ka⸱ṭā⸱nu⸱dham⸱me⸱na taṁ diṭ⸱ṭhiṁ ap⸱pa⸱ṭi⸱nis⸱saṭ⸱ṭhe⸱na sad⸱dhiṁ sam⸱bhuñ⸱jey⸱ya vā saṁ⸱va⸱sey⸱ya vā sa⸱ha vā sey⸱yaṁ kap⸱pey⸱ya, "
 "ṭhiṭ"____"i⸱me diṭ⸱ṭhiṭ⸱ṭhā⸱nā e⸱vaṁ⸱ga⸱hi⸱tā e⸱vaṁ⸱pa⸱rā⸱maṭ⸱ṭhā e⸱vaṁ⸱ga⸱ti⸱kā bha⸱van⸱ti e⸱vaṁa⸱bhi⸱sam⸱pa⸱rā⸱yā⸱’ti, "
 "ṭhul"____"yo pa⸱na bhik⸱khu o⸱tiṇ⸱ṇo vi⸱pa⸱ri⸱ṇa⸱te⸱na cit⸱te⸱na mā⸱tu⸱gā⸱maṁ duṭ⸱ṭhul⸱lā⸱hi vā⸱cā⸱hi o⸱bhā⸱sey⸱ya. "
 "ṭhuṁ"____"tañ⸱ce añ⸱ñā⸱ta⸱ko ga⸱ha⸱pa⸱ti vā ga⸱ha⸱pa⸱tā⸱nī vā ba⸱hū⸱hi cī⸱va⸱re⸱hi a⸱bhi⸱haṭ⸱ṭhuṁ pa⸱vā⸱rey⸱ya, "
 "ṭiṁ"____"sañ⸱ñā⸱ci⸱kā⸱ya pa⸱na bhik⸱khu⸱nā ku⸱ṭiṁ kā⸱ra⸱ya⸱mā⸱ne⸱na as⸱sā⸱mi⸱kaṁ at⸱tud⸱de⸱saṁ pa⸱mā⸱ṇi⸱kā kā⸱re⸱tab⸱bā, "
 "ṭthā"____"ku⸱lā⸱ni c’ ā⸱ya⸱sma⸱tā duṭ⸱ṭthā⸱ni dis⸱san⸱ti c’e⸱va suy⸱yan⸱ti ca; "
 
*/
 
 